<a href="https://cognitiveclass.ai/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkRP0321ENSkillsNetwork25371262-2021-01-01">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/M1_R_Basics/images/IDSNlogo.png" width="200" align="center">
</a>

<h1>OpenWeather APIs Calls</h1>

Estimated time needed: **40** minutes

## Lab Overview:

In this lab, you will be collecting real-time current and forecasted weather data for cities using the **OpenWeather API**. It can give you current weather data for any location including over 200,000 cities and 5 day forecasts for free (with limited API usage). You just need to use HTTP requests to call those weather APIs and get the weather data.

You will be given instructions to set up a free OpenWeather API account with an API key for authentication. Then, you will be shown, with code examples, how to get the current weather for a given city. After you are familiar with OpenWeather API, you will be asked to get 5-day forecast data for a list of cities.

## Setup OpenWeather API account

You can create an OpenWeather API account [here](https://home.openweathermap.org/users/sign_up?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkRP0321ENSkillsNetwork25371262-2021-01-01). After your account has been created and verified, you can go to Account -> My API Keys:

<a href="https://cognitiveclass.ai/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkRP0321ENSkillsNetwork25371262-2021-01-01">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/module_1/images/l2-openweather-apikey.png" width="400" align="center">
</a>

and find your API key here:

<a href="https://cognitiveclass.ai/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkRP0321ENSkillsNetwork25371262-2021-01-01">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/module_1/images/l2-openweather-apikey-value.png" width="400" align="center">
</a>

Now mark down your generated API key, which will be used to authenticate your HTTP requests to OpenWeather API.

Note that a new API key may take some time to be activated. You may quickly try the following URL using a web browser.

With the `{your_api_key}` URL parameter replaced by your own API key and go to the following URL:

[https://api.openweathermap.org/data/2.5/weather?q=Seoul&appid={your_api_key}](https://api.openweathermap.org/data/2.5/weather?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkRP0321ENSkillsNetwork25371262-2021-01-01&q=Seoul&appid=%7Byour_api_key%7D)

until you see some weather data returned (instead of 401 or other error status), similar to the following JSON result:

```
{"coord":{"lon":126.9778,"lat":37.5683},
"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01n"}],
"base":"stations",
"main":{"temp":285.16,"feels_like":284.04,"temp_min":284.15,"temp_max":287.15,"pressure":1020,"humidity":62},
"visibility":10000,
"wind":{"speed":1.03,"deg":220},"clouds":{"all":0},"dt":1617718307,"sys":{"type":1,"id":8105,"country":"KR","sunrise":1617657021,"sunset":1617703103},"timezone":32400,"id":1835848,"name":"Seoul","cod":200}
```

## Coding Practice: Get the current weather data for a city using OpenWeather API

First import `httr` library

In [1]:
import requests
import json
import pandas as pd
pd.options.display.max_columns = None
pd.options.display.max_rows = None

The API base URL to get current weather is [https://api.openweathermap.org/data/2.5/weather](https://api.openweathermap.org/data/2.5/weather?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkRP0321ENSkillsNetwork25371262-2021-01-01)

In [2]:
# URL for Current Weather API
current_weather_url = 'https://api.openweathermap.org/data/2.5/weather?'

Next, let's create a list to hold URL parameters for current weather API

In [3]:
# need to be replaced by your real API key
your_api_key = "277a72f5a19ff756ca573d7eaf5e56d9"
# Input `q` is the city name
city = "Seoul"
# Input `appid` is your API KEY, 
appid = your_api_key
# Input `units` are preferred units such as Metric or Imperial
units = "&units=metric"
#current_query <- list(q = "Seoul", appid = your_api_key, units="metric")

Now we can make a HTTP request to the current weather API

In [4]:
#response = requests.get(current_weather_url+"q="+city+"&appid="+appid+units)

In [5]:
#response = list(requests.get(current_weather_url+"q="+city+"&appid="+appid+units))

In [6]:
response_json = requests.get(current_weather_url+"q="+city+"&appid="+appid+units).json()

If we check the response type, we can see it is in JSON format

In [7]:
#response

In [8]:
response_json

{'coord': {'lon': 126.9778, 'lat': 37.5683},
 'weather': [{'id': 801,
   'main': 'Clouds',
   'description': 'few clouds',
   'icon': '02d'}],
 'base': 'stations',
 'main': {'temp': 18.78,
  'feels_like': 18.49,
  'temp_min': 16.69,
  'temp_max': 21.23,
  'pressure': 1002,
  'humidity': 68},
 'visibility': 10000,
 'wind': {'speed': 4.62, 'deg': 232, 'gust': 6.74},
 'clouds': {'all': 20},
 'dt': 1622770572,
 'sys': {'type': 1,
  'id': 8105,
  'country': 'KR',
  'sunrise': 1622751104,
  'sunset': 1622803759},
 'timezone': 32400,
 'id': 1835848,
 'name': 'Seoul',
 'cod': 200}

In [9]:
#type(response)

In [10]:
type(response_json)

dict

JSON is an open standard file and data interchange format that uses human-readable text to store and transmit data objects. To read the JSON HTTP response, you can use the `content()` function to parse it as a named list in R.

In [11]:
#response.text

In [12]:
#data = response.json()

If you use the `class()` function, you can see it is a R `List` object

In [13]:
#type(data)

Now let's print the JSON result.

In [14]:
response_json

{'coord': {'lon': 126.9778, 'lat': 37.5683},
 'weather': [{'id': 801,
   'main': 'Clouds',
   'description': 'few clouds',
   'icon': '02d'}],
 'base': 'stations',
 'main': {'temp': 18.78,
  'feels_like': 18.49,
  'temp_min': 16.69,
  'temp_max': 21.23,
  'pressure': 1002,
  'humidity': 68},
 'visibility': 10000,
 'wind': {'speed': 4.62, 'deg': 232, 'gust': 6.74},
 'clouds': {'all': 20},
 'dt': 1622770572,
 'sys': {'type': 1,
  'id': 8105,
  'country': 'KR',
  'sunrise': 1622751104,
  'sunset': 1622803759},
 'timezone': 32400,
 'id': 1835848,
 'name': 'Seoul',
 'cod': 200}

In [15]:
response_json.keys()

dict_keys(['coord', 'weather', 'base', 'main', 'visibility', 'wind', 'clouds', 'dt', 'sys', 'timezone', 'id', 'name', 'cod'])

In [16]:
response_json.values()

dict_values([{'lon': 126.9778, 'lat': 37.5683}, [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'stations', {'temp': 18.78, 'feels_like': 18.49, 'temp_min': 16.69, 'temp_max': 21.23, 'pressure': 1002, 'humidity': 68}, 10000, {'speed': 4.62, 'deg': 232, 'gust': 6.74}, {'all': 20}, 1622770572, {'type': 1, 'id': 8105, 'country': 'KR', 'sunrise': 1622751104, 'sunset': 1622803759}, 32400, 1835848, 'Seoul', 200])

In [17]:
response_json["coord"]["lon"]

126.9778

In [18]:
response_json["weather"][0]["main"]

'Clouds'

It contains very detailed weather data about the city of `Seoul`. Feel free to try other cities as well. We need to convert the named list to a data frame so that we can use data frame operations to process the data. Below is a simple example, which you may implement your own way to convert it to a data frame.

In [19]:
df_current_weather = pd.DataFrame()

In [20]:
# Create empty lists to store the JSON Data
weather = []
visibility = []
temp = []
temp_min = []
temp_max = []
pressure = []
humidity = []
wind_speed = []
wind_deg = []

Now assign the values in the `json_result` list into different vectors

In [21]:
# # $weather is also a list with one element, its $main element indicates the weather status such as clear or rain
weather.append(response_json["weather"][0]["main"])
# # Get Visibility
visibility.append(response_json['visibility'])
# # Get current temperature 
temp.append(response_json['main']['temp'])
# # Get min temperature 
temp_min.append(response_json['main']['temp_min'])
# # Get max temperature 
temp_max.append(response_json['main']['temp_max'])
# # Get pressure
pressure.append(response_json['main']['pressure'])
# # Get humidity
humidity.append(response_json['main']['humidity'])
# # Get wind speed
wind_speed.append(response_json['wind']['speed'])
# # Get wind direction
wind_deg.append(response_json['wind']['deg'])

In [22]:
wind_deg

[232]

Combine all vectors as columns of a data frame

In [23]:
# Write Lists to DataFrame
df_current_weather['weather'] = weather
df_current_weather['visibility'] = visibility
df_current_weather['temperature'] = temp
df_current_weather['temperature_min'] = temp_min
df_current_weather['temperature_max'] = temp_max
df_current_weather['pressure'] = pressure
df_current_weather['humidity'] = humidity
df_current_weather['wind_speed'] = wind_speed
df_current_weather['wind_degree'] = wind_deg

In [24]:
# Check the generated data frame
print(df_current_weather)

  weather  visibility  temperature  temperature_min  temperature_max  \
0  Clouds       10000        18.78            16.69            21.23

   pressure  humidity  wind_speed  wind_degree
0      1002        68        4.62          232

In [25]:
df_current_weather

,weather,visibility,temperature,temperature_min,temperature_max,pressure,humidity,wind_speed,wind_degree
0,Clouds,10000,18.78,16.69,21.23,1002,68,4.62,232

# TASK:  Get 5-day weather forecasts for a list of cities using the OpenWeather API

Now you should be familiar with the usage of OpenWeather API. Next, you need to complete a task to get 5-day weather forecasts for a list of cities

_TODO:_ Write a function to return a data frame containing 5-day weather forecasts for a list of cities

## Get forecast data for a given city list

In [26]:
# URL for Current Weather API
forecast_weather_url = 'http://api.openweathermap.org/data/2.5/forecast?'

Next, let's create a list to hold URL parameters for current weather API

### Seoul

In [27]:
# need to be replaced by your real API key
your_api_key = "277a72f5a19ff756ca573d7eaf5e56d9"
# Input `q` is the city name
city = "Seoul"
# Input `appid` is your API KEY, 
appid = your_api_key
# Input `units` are preferred units such as Metric or Imperial
units = "&units=metric"
#current_query <- list(q = "Seoul", appid = your_api_key, units="metric")

In [28]:
forecast_response_json = requests.get(forecast_weather_url+"q="+city+"&appid="+appid).json()

In [29]:
forecast_response_json

{'cod': '200',
 'message': 0,
 'cnt': 40,
 'list': [{'dt': 1622775600,
   'main': {'temp': 292.14,
    'feels_like': 291.87,
    'temp_min': 292.14,
    'temp_max': 295.52,
    'pressure': 1002,
    'sea_level': 1002,
    'grnd_level': 995,
    'humidity': 68,
    'temp_kf': -3.38},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 20},
   'wind': {'speed': 5.42, 'deg': 232, 'gust': 7.87},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-04 03:00:00'},
  {'dt': 1622786400,
   'main': {'temp': 293.58,
    'feels_like': 293.09,
    'temp_min': 293.58,
    'temp_max': 296.46,
    'pressure': 1002,
    'sea_level': 1002,
    'grnd_level': 995,
    'humidity': 54,
    'temp_kf': -2.88},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 13},
   'wind': {'speed': 6.8, 'deg': 233, 'gust': 10.36},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-04 06:00:00'},
  {'dt': 1622797200,
   'main': {'temp': 293.77,
    'feels_like': 293.11,
    'temp_min': 293.77,
    'temp_max': 294.59,
    'pressure': 1001,
    'sea_level': 1001,
    'grnd_level': 994,
    'humidity': 47,
    'temp_kf': -0.82},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 7},
   'wind': {'speed': 5.72, 'deg': 229, 'gust': 10.69},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-04 09:00:00'},
  {'dt': 1622808000,
   'main': {'temp': 291.71,
    'feels_like': 290.95,
    'temp_min': 291.71,
    'temp_max': 291.71,
    'pressure': 1001,
    'sea_level': 1001,
    'grnd_level': 994,
    'humidity': 51,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 0},
   'wind': {'speed': 4.03, 'deg': 191, 'gust': 12.12},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-04 12:00:00'},
  {'dt': 1622818800,
   'main': {'temp': 290.45,
    'feels_like': 289.7,
    'temp_min': 290.45,
    'temp_max': 290.45,
    'pressure': 1001,
    'sea_level': 1001,
    'grnd_level': 994,
    'humidity': 56,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 11},
   'wind': {'speed': 3.47, 'deg': 186, 'gust': 12.67},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-04 15:00:00'},
  {'dt': 1622829600,
   'main': {'temp': 290.19,
    'feels_like': 289.49,
    'temp_min': 290.19,
    'temp_max': 290.19,
    'pressure': 1000,
    'sea_level': 1000,
    'grnd_level': 994,
    'humidity': 59,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 28},
   'wind': {'speed': 3.97, 'deg': 193, 'gust': 13.63},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-04 18:00:00'},
  {'dt': 1622840400,
   'main': {'temp': 289.77,
    'feels_like': 289.29,
    'temp_min': 289.77,
    'temp_max': 289.77,
    'pressure': 1000,
    'sea_level': 1000,
    'grnd_level': 994,
    'humidity': 69,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 72},
   'wind': {'speed': 4.2, 'deg': 196, 'gust': 11.19},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-04 21:00:00'},
  {'dt': 1622851200,
   'main': {'temp': 293.31,
    'feels_like': 293.13,
    'temp_min': 293.31,
    'temp_max': 293.31,
    'pressure': 1001,
    'sea_level': 1001,
    'grnd_level': 995,
    'humidity': 67,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 45},
   'wind': {'speed': 5.76, 'deg': 221, 'gust': 7.45},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-05 00:00:00'},
  {'dt': 1622862000,
   'main': {'temp': 296.85,
    'feels_like': 296.63,
    'temp_min': 296.85,
    'temp_max': 296.85,
    'pressure': 1000,
    'sea_level': 1000,
    'grnd_level': 994,
    'humidity': 52,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 30},
   'wind': {'speed': 5.03, 'deg': 231, 'gust': 6.35},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-05 03:00:00'},
  {'dt': 1622872800,
   'main': {'temp': 298.38,
    'feels_like': 297.98,
    'temp_min': 298.38,
    'temp_max': 298.38,
    'pressure': 999,
    'sea_level': 999,
    'grnd_level': 993,
    'humidity': 39,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 15},
   'wind': {'speed': 5.3, 'deg': 234, 'gust': 8.34},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-05 06:00:00'},
  {'dt': 1622883600,
   'main': {'temp': 296.26,
    'feels_like': 295.8,
    'temp_min': 296.26,
    'temp_max': 296.26,
    'pressure': 1000,
    'sea_level': 1000,
    'grnd_level': 994,
    'humidity': 45,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 0},
   'wind': {'speed': 4.99, 'deg': 237, 'gust': 7.82},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-05 09:00:00'},
  {'dt': 1622894400,
   'main': {'temp': 292.32,
    'feels_like': 292.2,
    'temp_min': 292.32,
    'temp_max': 292.32,
    'pressure': 1003,
    'sea_level': 1003,
    'grnd_level': 996,
    'humidity': 73,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 0},
   'wind': {'speed': 3.07, 'deg': 219, 'gust': 7.68},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-05 12:00:00'},
  {'dt': 1622905200,
   'main': {'temp': 290.86,
    'feels_like': 290.91,
    'temp_min': 290.86,
    'temp_max': 290.86,
    'pressure': 1004,
    'sea_level': 1004,
    'grnd_level': 997,
    'humidity': 85,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 0},
   'wind': {'speed': 2.55, 'deg': 193, 'gust': 7.35},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-05 15:00:00'},
  {'dt': 1622916000,
   'main': {'temp': 289.86,
    'feels_like': 289.99,
    'temp_min': 289.86,
    'temp_max': 289.86,
    'pressure': 1005,
    'sea_level': 1005,
    'grnd_level': 998,
    'humidity': 92,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 7},
   'wind': {'speed': 1.96, 'deg': 170, 'gust': 5.06},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-05 18:00:00'},
  {'dt': 1622926800,
   'main': {'temp': 290.78,
    'feels_like': 290.74,
    'temp_min': 290.78,
    'temp_max': 290.78,
    'pressure': 1006,
    'sea_level': 1006,
    'grnd_level': 1000,
    'humidity': 82,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 93},
   'wind': {'speed': 2.53, 'deg': 171, 'gust': 5.3},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-05 21:00:00'},
  {'dt': 1622937600,
   'main': {'temp': 292.85,
    'feels_like': 292.76,
    'temp_min': 292.85,
    'temp_max': 292.85,
    'pressure': 1007,
    'sea_level': 1007,
    'grnd_level': 1001,
    'humidity': 72,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 97},
   'wind': {'speed': 2.43, 'deg': 183, 'gust': 3.94},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-06 00:00:00'},
  {'dt': 1622948400,
   'main': {'temp': 294.77,
    'feels_like': 294.76,
    'temp_min': 294.77,
    'temp_max': 294.77,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 1001,
    'humidity': 68,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 99},
   'wind': {'speed': 1.99, 'deg': 189, 'gust': 3.55},
   'visibility': 10000,
   'pop': 0.03,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-06 03:00:00'},
  {'dt': 1622959200,
   'main': {'temp': 300.59,
    'feels_like': 300.41,
    'temp_min': 300.59,
    'temp_max': 300.59,
    'pressure': 1006,
    'sea_level': 1006,
    'grnd_level': 1000,
    'humidity': 41,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 62},
   'wind': {'speed': 3.73, 'deg': 219, 'gust': 5.1},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-06 06:00:00'},
  {'dt': 1622970000,
   'main': {'temp': 296.8,
    'feels_like': 296.79,
    'temp_min': 296.8,
    'temp_max': 296.8,
    'pressure': 1007,
    'sea_level': 1007,
    'grnd_level': 1000,
    'humidity': 60,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 55},
   'wind': {'speed': 4.06, 'deg': 235, 'gust': 5.55},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-06 09:00:00'},
  {'dt': 1622980800,
   'main': {'temp': 293.32,
    'feels_like': 293.38,
    'temp_min': 293.32,
    'temp_max': 293.32,
    'pressure': 1009,
    'sea_level': 1009,
    'grnd_level': 1003,
    'humidity': 76,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 47},
   'wind': {'speed': 2.49, 'deg': 228, 'gust': 5.9},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-06 12:00:00'},
  {'dt': 1622991600,
   'main': {'temp': 291.71,
    'feels_like': 291.87,
    'temp_min': 291.71,
    'temp_max': 291.71,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 1004,
    'humidity': 86,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 77},
   'wind': {'speed': 2.49, 'deg': 186, 'gust': 5.22},
   'visibility': 10000,
   'pop': 0.37,
   'rain': {'3h': 0.45},
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-06 15:00:00'},
  {'dt': 1623002400,
   'main': {'temp': 291.33,
    'feels_like': 291.45,
    'temp_min': 291.33,
    'temp_max': 291.33,
    'pressure': 1012,
    'sea_level': 1012,
    'grnd_level': 1006,
    'humidity': 86,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 79},
   'wind': {'speed': 1.56, 'deg': 204, 'gust': 3.43},
   'visibility': 10000,
   'pop': 0.26,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-06 18:00:00'},
  {'dt': 1623013200,
   'main': {'temp': 291.01,
    'feels_like': 291.12,
    'temp_min': 291.01,
    'temp_max': 291.01,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 1006,
    'humidity': 87,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 78},
   'wind': {'speed': 1.41, 'deg': 144, 'gust': 2.27},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-06 21:00:00'},
  {'dt': 1623024000,
   'main': {'temp': 294.92,
    'feels_like': 294.8,
    'temp_min': 294.92,
    'temp_max': 294.92,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 1007,
    'humidity': 63,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 77},
   'wind': {'speed': 1.57, 'deg': 173, 'gust': 2.27},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-07 00:00:00'},
  {'dt': 1623034800,
   'main': {'temp': 299.68,
    'feels_like': 299.68,
    'temp_min': 299.68,
    'temp_max': 299.68,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 1007,
    'humidity': 44,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 96},
   'wind': {'speed': 2.32, 'deg': 226, 'gust': 3.17},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-07 03:00:00'},
  {'dt': 1623045600,
   'main': {'temp': 301.36,
    'feels_like': 300.5,
    'temp_min': 301.36,
    'temp_max': 301.36,
    'pressure': 1012,
    'sea_level': 1012,
    'grnd_level': 1006,
    'humidity': 32,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 98},
   'wind': {'speed': 2.64, 'deg': 252, 'gust': 3.02},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-07 06:00:00'},
  {'dt': 1623056400,
   'main': {'temp': 297.93,
    'feels_like': 297.66,
    'temp_min': 297.93,
    'temp_max': 297.93,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 1007,
    'humidity': 46,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.38, 'deg': 39, 'gust': 3.83},
   'visibility': 10000,
   'pop': 0.03,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-07 09:00:00'},
  {'dt': 1623067200,
   'main': {'temp': 296.73,
    'feels_like': 296.48,
    'temp_min': 296.73,
    'temp_max': 296.73,
    'pressure': 1014,
    'sea_level': 1014,
    'grnd_level': 1007,
    'humidity': 51,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.6, 'deg': 190, 'gust': 2.14},
   'visibility': 10000,
   'pop': 0.01,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-07 12:00:00'},
  {'dt': 1623078000,
   'main': {'temp': 294.51,
    'feels_like': 294.24,
    'temp_min': 294.51,
    'temp_max': 294.51,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1008,
    'humidity': 59,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 0.65, 'deg': 347, 'gust': 0.74},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-07 15:00:00'},
  {'dt': 1623088800,
   'main': {'temp': 294.05,
    'feels_like': 293.84,
    'temp_min': 294.05,
    'temp_max': 294.05,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1008,
    'humidity': 63,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 0.93, 'deg': 86, 'gust': 0.88},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-07 18:00:00'},
  {'dt': 1623099600,
   'main': {'temp': 293.24,
    'feels_like': 293.03,
    'temp_min': 293.24,
    'temp_max': 293.24,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1009,
    'humidity': 66,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.09, 'deg': 95, 'gust': 1.08},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-07 21:00:00'},
  {'dt': 1623110400,
   'main': {'temp': 294.59,
    'feels_like': 294.41,
    'temp_min': 294.59,
    'temp_max': 294.59,
    'pressure': 1016,
    'sea_level': 1016,
    'grnd_level': 1009,
    'humidity': 62,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 99},
   'wind': {'speed': 1.22, 'deg': 56, 'gust': 1.58},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-08 00:00:00'},
  {'dt': 1623121200,
   'main': {'temp': 301.87,
    'feels_like': 300.97,
    'temp_min': 301.87,
    'temp_max': 301.87,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1009,
    'humidity': 33,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 99},
   'wind': {'speed': 1.16, 'deg': 69, 'gust': 1.26},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-08 03:00:00'},
  {'dt': 1623132000,
   'main': {'temp': 305.18,
    'feels_like': 303.42,
    'temp_min': 305.18,
    'temp_max': 305.18,
    'pressure': 1014,
    'sea_level': 1014,
    'grnd_level': 1007,
    'humidity': 24,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 90},
   'wind': {'speed': 0.28, 'deg': 64, 'gust': 0.75},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-08 06:00:00'},
  {'dt': 1623142800,
   'main': {'temp': 304.15,
    'feels_like': 302.49,
    'temp_min': 304.15,
    'temp_max': 304.15,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 1007,
    'humidity': 25,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 99},
   'wind': {'speed': 0.69, 'deg': 318, 'gust': 0.85},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-08 09:00:00'},
  {'dt': 1623153600,
   'main': {'temp': 300,
    'feels_like': 299.81,
    'temp_min': 300,
    'temp_max': 300,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 1007,
    'humidity': 38,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 98},
   'wind': {'speed': 0.96, 'deg': 18, 'gust': 1.26},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-08 12:00:00'},
  {'dt': 1623164400,
   'main': {'temp': 297.55,
    'feels_like': 297.33,
    'temp_min': 297.55,
    'temp_max': 297.55,
    'pressure': 1014,
    'sea_level': 1014,
    'grnd_level': 1007,
    'humidity': 49,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.65, 'deg': 41, 'gust': 1.95},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-08 15:00:00'},
  {'dt': 1623175200,
   'main': {'temp': 295.83,
    'feels_like': 295.59,
    'temp_min': 295.83,
    'temp_max': 295.83,
    'pressure': 1014,
    'sea_level': 1014,
    'grnd_level': 1007,
    'humidity': 55,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 99},
   'wind': {'speed': 1.27, 'deg': 82, 'gust': 1.27},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-08 18:00:00'},
  {'dt': 1623186000,
   'main': {'temp': 294.96,
    'feels_like': 294.76,
    'temp_min': 294.96,
    'temp_max': 294.96,
    'pressure': 1014,
    'sea_level': 1014,
    'grnd_level': 1007,
    'humidity': 60,
    'temp_kf': 0},
   'weather': [{'id': 804,

In [30]:
df_predictions_seoul = pd.DataFrame()

In [31]:
# Create empty lists to store the JSON Data
prediction_num = 0
list_prediction_num = []
city = []
weather = []
visibility = []
temp = []
temp_min = []
temp_max = []
pressure = []
humidity = []
wind_speed = []
wind_deg = []

In [32]:
for num_forecasts in forecast_response_json['list']:
    df_predictions_seoul['prediction_num'] = prediction_num
    list_prediction_num.append(prediction_num)
    city.append(forecast_response_json['city']['name'])
    weather.append(forecast_response_json['list'][prediction_num]['weather'][0]['main'])
    visibility.append(forecast_response_json['list'][prediction_num]['visibility'])
    temp.append(forecast_response_json['list'][prediction_num]['main']['temp'])
    temp_min.append(forecast_response_json['list'][prediction_num]['main']['temp_min'])
    temp_max.append(forecast_response_json['list'][prediction_num]['main']['temp_max'])
    pressure.append(forecast_response_json['list'][prediction_num]['main']['pressure'])
    humidity.append(forecast_response_json['list'][prediction_num]['main']['humidity'])
    wind_speed.append(forecast_response_json['list'][prediction_num]['wind']['speed'])
    wind_deg.append(forecast_response_json['list'][prediction_num]['wind']['deg'])
    prediction_num += 1

In [33]:
# df_predictions['prediction_num'] = prediction_num
# list_prediction_num.append(prediction_num)
# city.append(forecast_response_json['city']['name'])
# weather.append(forecast_response_json['list'][0]['weather'][0]['main'])
# visibility.append(forecast_response_json['list'][0]['visibility'])
# temp.append(forecast_response_json['list'][0]['main']['temp'])
# temp_min.append(forecast_response_json['list'][0]['main']['temp_min'])
# temp_max.append(forecast_response_json['list'][0]['main']['temp_max'])
# pressure.append(forecast_response_json['list'][0]['main']['pressure'])
# humidity.append(forecast_response_json['list'][0]['main']['humidity'])
# wind_speed.append(forecast_response_json['list'][0]['wind']['speed'])
# wind_deg.append(forecast_response_json['list'][0]['wind']['deg'])

In [34]:
#wind_deg

Complete and call `get_weather_forecast_by_cities` function with a list of cities, and write the data frame into a csv file called `cities_weather_forecast.csv`

In [35]:
# Write Lists to DataFrame
df_predictions_seoul['prediction_num'] = list_prediction_num
df_predictions_seoul['city'] = city
df_predictions_seoul['weather'] = weather
df_predictions_seoul['visibility'] = visibility
df_predictions_seoul['temperature'] = temp
df_predictions_seoul['temperature_min'] = temp_min
df_predictions_seoul['temperature_max'] = temp_max
df_predictions_seoul['pressure'] = pressure
df_predictions_seoul['humidity'] = humidity
df_predictions_seoul['wind_speed'] = wind_speed
df_predictions_seoul['wind_degree'] = wind_deg

In [36]:
df_predictions_seoul

,prediction_num,city,weather,visibility,temperature,temperature_min,temperature_max,pressure,humidity,wind_speed,wind_degree
0,0,Seoul,Clouds,10000,292.14,292.14,295.52,1002,68,5.42,232
1,1,Seoul,Clouds,10000,293.58,293.58,296.46,1002,54,6.80,233
2,2,Seoul,Clear,10000,293.77,293.77,294.59,1001,47,5.72,229
3,3,Seoul,Clear,10000,291.71,291.71,291.71,1001,51,4.03,191
4,4,Seoul,Clouds,10000,290.45,290.45,290.45,1001,56,3.47,186
5,5,Seoul,Clouds,10000,290.19,290.19,290.19,1000,59,3.97,193
6,6,Seoul,Clouds,10000,289.77,289.77,289.77,1000,69,4.20,196
7,7,Seoul,Clouds,10000,293.31,293.31,293.31,1001,67,5.76,221
8,8,Seoul,Clouds,10000,296.85,296.85,296.85,1000,52,5.03,231
9,9,Seoul,Clouds,10000,298.38,298.38,298.38,999,39,5.30,234
10,10,Seoul,Clear,10000,296.26,296.26,296.26,1000,45,4.99,237
11,11,Seoul,Clear,10000,292.32,292.32,292.32,1003,73,3.07,219
12,12,Seoul,Clear,10000,290.86,290.86,290.86,1004,85,2.55,193
13,13,Seoul,Clear,10000,289.86,289.86,289.86,1005,92,1.96,170
14,14,Seoul,Clouds,10000,290.78,290.78,290.78,1006,82,2.53,171
15,15,Seoul,Clouds,10000,292.85,292.85,292.85,1007,72,2.43,183
16,16,Seoul,Clouds,10000,294.77,294.77,294.77,1008,68,1.99,189
17,17,Seoul,Clouds,10000,300.59,300.59,300.59,1006,41,3.73,219
18,18,Seoul,Clouds,10000,296.80,296.80,296.80,1007,60,4.06,235
19,19,Seoul,Clouds,10000,293.32,293.32,293.32,1009,76,2.49,228
20,20,Seoul,Rain,10000,291.71,291.71,291.71,1010,86,2.49,186
21,21,Seoul,Clouds,10000,291.33,291.33,291.33,1012,86,1.56,204
22,22,Seoul,Clouds,10000,291.01,291.01,291.01,1013,87,1.41,144
23,23,Seoul,Clouds,10000,294.92,294.92,294.92,1013,63,1.57,173
24,24,Seoul,Clouds,10000,299.68,299.68,299.68,1013,44,2.32,226
25,25,Seoul,Clouds,10000,301.36,301.36,301.36,1012,32,2.64,252
26,26,Seoul,Clouds,10000,297.93,297.93,297.93,1013,46,1.38,39
27,27,Seoul,Clouds,10000,296.73,296.73,296.73,1014,51,1.60,190
28,28,Seoul,Clouds,10000,294.51,294.51,294.51,1015,59,0.65,347
29,29,Seoul,Clouds,10000,294.05,294.05,294.05,1015,63,0.93,86
30,30,Seoul,Clouds,10000,293.24,293.24,293.24,1015,66,1.09,95
31,31,Seoul,Clouds,10000,294.59,294.59,294.59,1016,62,1.22,56
32,32,Seoul,Clouds,10000,301.87,301.87,301.87,1015,33,1.16,69
33,33,Seoul,Clouds,10000,305.18,305.18,305.18,1014,24,0.28,64
34,34,Seoul,Clouds,10000,304.15,304.15,304.15,1013,25,0.69,318
35,35,Seoul,Clouds,10000,300.00,300.00,300.00,1013,38,0.96,18
36,36,Seoul,Clouds,10000,297.55,297.55,297.55,1014,49,1.65,41
37,37,Seoul,Clouds,10000,295.83,295.83,295.83,1014,55,1.27,82
38,38,Seoul,Clouds,10000,294.96,294.96,294.96,1014,60,1.41,67
39,39,Seoul,Clouds,10000,299.96,299.96,299.96,1014,46,1.59,79

In [37]:
#Save to csv
#df_predictions_seoul.to_csv("seoul.csv", index=False)

### Washington, D.C

In [38]:
# URL for Current Weather API
forecast_weather_url = 'http://api.openweathermap.org/data/2.5/forecast?'

In [39]:
# need to be replaced by your real API key
your_api_key = "277a72f5a19ff756ca573d7eaf5e56d9"
# Input `q` is the city name
city = "Washington, D.C."
# Input `appid` is your API KEY, 
appid = your_api_key
# Input `units` are preferred units such as Metric or Imperial
units = "&units=metric"
#current_query <- list(q = "Seoul", appid = your_api_key, units="metric")

In [40]:
forecast_response_json = requests.get(forecast_weather_url+"q="+city+"&appid="+appid).json()

In [41]:
forecast_response_json

{'cod': '200',
 'message': 0,
 'cnt': 40,
 'list': [{'dt': 1622775600,
   'main': {'temp': 300.48,
    'feels_like': 299.82,
    'temp_min': 297.02,
    'temp_max': 300.48,
    'pressure': 1007,
    'sea_level': 1007,
    'grnd_level': 952,
    'humidity': 31,
    'temp_kf': 3.46},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 2},
   'wind': {'speed': 2.81, 'deg': 332, 'gust': 4.21},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-04 03:00:00'},
  {'dt': 1622786400,
   'main': {'temp': 296.88,
    'feels_like': 296.48,
    'temp_min': 289.68,
    'temp_max': 296.88,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 953,
    'humidity': 45,
    'temp_kf': 7.2},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 4},
   'wind': {'speed': 2.88, 'deg': 285, 'gust': 3.02},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-04 06:00:00'},
  {'dt': 1622797200,
   'main': {'temp': 291.71,
    'feels_like': 291.32,
    'temp_min': 287.32,
    'temp_max': 291.71,
    'pressure': 1009,
    'sea_level': 1009,
    'grnd_level': 953,
    'humidity': 65,
    'temp_kf': 4.39},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 11},
   'wind': {'speed': 2.72, 'deg': 282, 'gust': 2.84},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-04 09:00:00'},
  {'dt': 1622808000,
   'main': {'temp': 285.25,
    'feels_like': 284.71,
    'temp_min': 285.25,
    'temp_max': 285.25,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 953,
    'humidity': 84,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 7},
   'wind': {'speed': 2.68, 'deg': 286, 'gust': 2.92},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-04 12:00:00'},
  {'dt': 1622818800,
   'main': {'temp': 292.3,
    'feels_like': 291.34,
    'temp_min': 292.3,
    'temp_max': 292.3,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 955,
    'humidity': 41,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 8},
   'wind': {'speed': 2.55, 'deg': 309, 'gust': 3.72},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-04 15:00:00'},
  {'dt': 1622829600,
   'main': {'temp': 298.55,
    'feels_like': 297.62,
    'temp_min': 298.55,
    'temp_max': 298.55,
    'pressure': 1009,
    'sea_level': 1009,
    'grnd_level': 954,
    'humidity': 18,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 14},
   'wind': {'speed': 2.83, 'deg': 332, 'gust': 4.91},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-04 18:00:00'},
  {'dt': 1622840400,
   'main': {'temp': 301.64,
    'feels_like': 300.13,
    'temp_min': 301.64,
    'temp_max': 301.64,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 953,
    'humidity': 13,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 39},
   'wind': {'speed': 2.56, 'deg': 311, 'gust': 5.31},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-04 21:00:00'},
  {'dt': 1622851200,
   'main': {'temp': 298.85,
    'feels_like': 297.95,
    'temp_min': 298.85,
    'temp_max': 298.85,
    'pressure': 1006,
    'sea_level': 1006,
    'grnd_level': 952,
    'humidity': 18,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 63},
   'wind': {'speed': 3.8, 'deg': 321, 'gust': 6.01},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-05 00:00:00'},
  {'dt': 1622862000,
   'main': {'temp': 292.21,
    'feels_like': 291.14,
    'temp_min': 292.21,
    'temp_max': 292.21,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 952,
    'humidity': 37,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 46},
   'wind': {'speed': 3.24, 'deg': 322, 'gust': 5.3},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-05 03:00:00'},
  {'dt': 1622872800,
   'main': {'temp': 284.92,
    'feels_like': 283.69,
    'temp_min': 284.92,
    'temp_max': 284.92,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 952,
    'humidity': 59,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 73},
   'wind': {'speed': 3.08, 'deg': 276, 'gust': 3.51},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-05 06:00:00'},
  {'dt': 1622883600,
   'main': {'temp': 282.75,
    'feels_like': 281.37,
    'temp_min': 282.75,
    'temp_max': 282.75,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 953,
    'humidity': 70,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.7, 'deg': 275, 'gust': 3.22},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-05 09:00:00'},
  {'dt': 1622894400,
   'main': {'temp': 282.21,
    'feels_like': 281.1,
    'temp_min': 282.21,
    'temp_max': 282.21,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 952,
    'humidity': 70,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 80},
   'wind': {'speed': 2.18, 'deg': 271, 'gust': 2.43},
   'visibility': 10000,
   'pop': 0.04,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-05 12:00:00'},
  {'dt': 1622905200,
   'main': {'temp': 287.62,
    'feels_like': 286.4,
    'temp_min': 287.62,
    'temp_max': 287.62,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 953,
    'humidity': 49,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 9},
   'wind': {'speed': 2.52, 'deg': 284, 'gust': 5.52},
   'visibility': 10000,
   'pop': 0.16,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-05 15:00:00'},
  {'dt': 1622916000,
   'main': {'temp': 290.03,
    'feels_like': 288.66,
    'temp_min': 290.03,
    'temp_max': 290.03,
    'pressure': 1009,
    'sea_level': 1009,
    'grnd_level': 953,
    'humidity': 34,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 21},
   'wind': {'speed': 3.65, 'deg': 282, 'gust': 6.53},
   'visibility': 10000,
   'pop': 0.16,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-05 18:00:00'},
  {'dt': 1622926800,
   'main': {'temp': 291.51,
    'feels_like': 290.18,
    'temp_min': 291.51,
    'temp_max': 291.51,
    'pressure': 1009,
    'sea_level': 1009,
    'grnd_level': 953,
    'humidity': 30,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 7},
   'wind': {'speed': 4.19, 'deg': 288, 'gust': 7.34},
   'visibility': 10000,
   'pop': 0.16,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-05 21:00:00'},
  {'dt': 1622937600,
   'main': {'temp': 289.02,
    'feels_like': 287.79,
    'temp_min': 289.02,
    'temp_max': 289.02,
    'pressure': 1009,
    'sea_level': 1009,
    'grnd_level': 953,
    'humidity': 43,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 7},
   'wind': {'speed': 4.95, 'deg': 287, 'gust': 8.69},
   'visibility': 10000,
   'pop': 0.2,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-06 00:00:00'},
  {'dt': 1622948400,
   'main': {'temp': 284.2,
    'feels_like': 283.06,
    'temp_min': 284.2,
    'temp_max': 284.2,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 953,
    'humidity': 65,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 59},
   'wind': {'speed': 2.99, 'deg': 289, 'gust': 5.12},
   'visibility': 10000,
   'pop': 0.2,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-06 03:00:00'},
  {'dt': 1622959200,
   'main': {'temp': 279.72,
    'feels_like': 278.05,
    'temp_min': 279.72,
    'temp_max': 279.72,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 955,
    'humidity': 90,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 59},
   'wind': {'speed': 2.33, 'deg': 309, 'gust': 2.45},
   'visibility': 10000,
   'pop': 0.2,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-06 06:00:00'},
  {'dt': 1622970000,
   'main': {'temp': 277.76,
    'feels_like': 275.55,
    'temp_min': 277.76,
    'temp_max': 277.76,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 955,
    'humidity': 92,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 17},
   'wind': {'speed': 2.55, 'deg': 286, 'gust': 2.71},
   'visibility': 10000,
   'pop': 0.08,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-06 09:00:00'},
  {'dt': 1622980800,
   'main': {'temp': 276.82,
    'feels_like': 274.45,
    'temp_min': 276.82,
    'temp_max': 276.82,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 956,
    'humidity': 90,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 13},
   'wind': {'speed': 2.53, 'deg': 289, 'gust': 2.72},
   'visibility': 10000,
   'pop': 0.08,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-06 12:00:00'},
  {'dt': 1622991600,
   'main': {'temp': 283.42,
    'feels_like': 281.91,
    'temp_min': 283.42,
    'temp_max': 283.42,
    'pressure': 1014,
    'sea_level': 1014,
    'grnd_level': 956,
    'humidity': 54,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 39},
   'wind': {'speed': 2, 'deg': 338, 'gust': 2.51},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-06 15:00:00'},
  {'dt': 1623002400,
   'main': {'temp': 288.51,
    'feels_like': 286.94,
    'temp_min': 288.51,
    'temp_max': 288.51,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 953,
    'humidity': 32,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 23},
   'wind': {'speed': 2.31, 'deg': 36, 'gust': 3.3},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-06 18:00:00'},
  {'dt': 1623013200,
   'main': {'temp': 292.6,
    'feels_like': 291.18,
    'temp_min': 292.6,
    'temp_max': 292.6,
    'pressure': 1006,
    'sea_level': 1006,
    'grnd_level': 951,
    'humidity': 22,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 90},
   'wind': {'speed': 1.61, 'deg': 186, 'gust': 3.61},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-06 21:00:00'},
  {'dt': 1623024000,
   'main': {'temp': 289.29,
    'feels_like': 287.87,
    'temp_min': 289.29,
    'temp_max': 289.29,
    'pressure': 1007,
    'sea_level': 1007,
    'grnd_level': 950,
    'humidity': 35,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 95},
   'wind': {'speed': 3.15, 'deg': 297, 'gust': 3.9},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-07 00:00:00'},
  {'dt': 1623034800,
   'main': {'temp': 286.79,
    'feels_like': 285.33,
    'temp_min': 286.79,
    'temp_max': 286.79,
    'pressure': 1006,
    'sea_level': 1006,
    'grnd_level': 949,
    'humidity': 43,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 8},
   'wind': {'speed': 1.81, 'deg': 312, 'gust': 3},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-07 03:00:00'},
  {'dt': 1623045600,
   'main': {'temp': 278.93,
    'feels_like': 276.87,
    'temp_min': 278.93,
    'temp_max': 278.93,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 951,
    'humidity': 78,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 5},
   'wind': {'speed': 2.63, 'deg': 285, 'gust': 2.82},
   'visibility': 10000,
   'pop': 0.04,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-07 06:00:00'},
  {'dt': 1623056400,
   'main': {'temp': 279.37,
    'feels_like': 277.44,
    'temp_min': 279.37,
    'temp_max': 279.37,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 952,
    'humidity': 70,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 69},
   'wind': {'speed': 2.57, 'deg': 298, 'gust': 3.21},
   'visibility': 10000,
   'pop': 0.32,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-07 09:00:00'},
  {'dt': 1623067200,
   'main': {'temp': 276.07,
    'feels_like': 273.44,
    'temp_min': 276.07,
    'temp_max': 276.07,
    'pressure': 1014,
    'sea_level': 1014,
    'grnd_level': 954,
    'humidity': 76,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 63},
   'wind': {'speed': 2.66, 'deg': 278, 'gust': 2.32},
   'visibility': 10000,
   'pop': 0.16,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-07 12:00:00'},
  {'dt': 1623078000,
   'main': {'temp': 282.94,
    'feels_like': 281.86,
    'temp_min': 282.94,
    'temp_max': 282.94,
    'pressure': 1014,
    'sea_level': 1014,
    'grnd_level': 956,
    'humidity': 45,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 0},
   'wind': {'speed': 2.31, 'deg': 329, 'gust': 3.01},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-07 15:00:00'},
  {'dt': 1623088800,
   'main': {'temp': 288.68,
    'feels_like': 287.07,
    'temp_min': 288.68,
    'temp_max': 288.68,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 955,
    'humidity': 30,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 25},
   'wind': {'speed': 1.96, 'deg': 81, 'gust': 1.7},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-07 18:00:00'},
  {'dt': 1623099600,
   'main': {'temp': 291.51,
    'feels_like': 290.11,
    'temp_min': 291.51,
    'temp_max': 291.51,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 954,
    'humidity': 27,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 4.11, 'deg': 92, 'gust': 2.92},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-07 21:00:00'},
  {'dt': 1623110400,
   'main': {'temp': 291.83,
    'feels_like': 290.46,
    'temp_min': 291.83,
    'temp_max': 291.83,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 952,
    'humidity': 27,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 3.37, 'deg': 107, 'gust': 3.1},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-08 00:00:00'},
  {'dt': 1623121200,
   'main': {'temp': 288.6,
    'feels_like': 287.14,
    'temp_min': 288.6,
    'temp_max': 288.6,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 951,
    'humidity': 36,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 0.51, 'deg': 168, 'gust': 0.61},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-08 03:00:00'},
  {'dt': 1623132000,
   'main': {'temp': 285.62,
    'feels_like': 283.97,
    'temp_min': 285.62,
    'temp_max': 285.62,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 951,
    'humidity': 40,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.9, 'deg': 274, 'gust': 1.59},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-08 06:00:00'},
  {'dt': 1623142800,
   'main': {'temp': 284.58,
    'feels_like': 282.93,
    'temp_min': 284.58,
    'temp_max': 284.58,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 950,
    'humidity': 44,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 0.97, 'deg': 267, 'gust': 0.9},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-08 09:00:00'},
  {'dt': 1623153600,
   'main': {'temp': 283.75,
    'feels_like': 282.38,
    'temp_min': 283.75,
    'temp_max': 283.75,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 950,
    'humidity': 58,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.49, 'deg': 278, 'gust': 2.73},
   'visibility': 10000,
   'pop': 0.2,
   'rain': {'3h': 0.19},
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-08 12:00:00'},
  {'dt': 1623164400,
   'main': {'temp': 283.48,
    'feels_like': 282.63,
    'temp_min': 283.48,
    'temp_max': 283.48,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 953,
    'humidity': 79,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.39, 'deg': 306, 'gust': 2.72},
   'visibility': 10000,
   'pop': 0.56,
   'rain': {'3h': 0.7},
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-08 15:00:00'},
  {'dt': 1623175200,
   'main': {'temp': 287.04,
    'feels_like': 285.95,
    'temp_min': 287.04,
    'temp_max': 287.04,
    'pressure': 1012,
    'sea_level': 1012,
    'grnd_level': 954,
    'humidity': 56,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 99},
   'wind': {'speed': 2.62, 'deg': 283, 'gust': 3.11},
   'visibility': 10000,
   'pop': 0.56,
   'rain': {'3h': 0.13},
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-08 18:00:00'},
  {'dt': 1623186000,
   'main': {'temp': 291.51,
    'feels_like': 290.16,
    'temp_min': 291.51,
    'temp_max': 291.51,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 955,
    'humidity': 29,
    'temp_kf': 0},
   'weather': [{'id': 500,

In [42]:
df_predictions_wash = pd.DataFrame()

In [43]:
# Create empty lists to store the JSON Data
prediction_num = 0
list_prediction_num = []
city = []
weather = []
visibility = []
temp = []
temp_min = []
temp_max = []
pressure = []
humidity = []
wind_speed = []
wind_deg = []

In [44]:
for num_forecasts in forecast_response_json['list']:
    df_predictions_wash['prediction_num'] = prediction_num
    list_prediction_num.append(prediction_num)
    city.append(forecast_response_json['city']['name'])
    weather.append(forecast_response_json['list'][prediction_num]['weather'][0]['main'])
    visibility.append(forecast_response_json['list'][prediction_num]['visibility'])
    temp.append(forecast_response_json['list'][prediction_num]['main']['temp'])
    temp_min.append(forecast_response_json['list'][prediction_num]['main']['temp_min'])
    temp_max.append(forecast_response_json['list'][prediction_num]['main']['temp_max'])
    pressure.append(forecast_response_json['list'][prediction_num]['main']['pressure'])
    humidity.append(forecast_response_json['list'][prediction_num]['main']['humidity'])
    wind_speed.append(forecast_response_json['list'][prediction_num]['wind']['speed'])
    wind_deg.append(forecast_response_json['list'][prediction_num]['wind']['deg'])
    prediction_num += 1

Complete and call `get_weather_forecast_by_cities` function with a list of cities, and write the data frame into a csv file called `cities_weather_forecast.csv`

In [45]:
# Write Lists to DataFrame
df_predictions_wash['prediction_num'] = list_prediction_num
df_predictions_wash['city'] = city
df_predictions_wash['weather'] = weather
df_predictions_wash['visibility'] = visibility
df_predictions_wash['temperature'] = temp
df_predictions_wash['temperature_min'] = temp_min
df_predictions_wash['temperature_max'] = temp_max
df_predictions_wash['pressure'] = pressure
df_predictions_wash['humidity'] = humidity
df_predictions_wash['wind_speed'] = wind_speed
df_predictions_wash['wind_degree'] = wind_deg

In [46]:
df_predictions_wash

,prediction_num,city,weather,visibility,temperature,temperature_min,temperature_max,pressure,humidity,wind_speed,wind_degree
0,0,Washington,Clear,10000,300.48,297.02,300.48,1007,31,2.81,332
1,1,Washington,Clear,10000,296.88,289.68,296.88,1008,45,2.88,285
2,2,Washington,Clouds,10000,291.71,287.32,291.71,1009,65,2.72,282
3,3,Washington,Clear,10000,285.25,285.25,285.25,1011,84,2.68,286
4,4,Washington,Clear,10000,292.30,292.30,292.30,1011,41,2.55,309
5,5,Washington,Clouds,10000,298.55,298.55,298.55,1009,18,2.83,332
6,6,Washington,Clouds,10000,301.64,301.64,301.64,1008,13,2.56,311
7,7,Washington,Clouds,10000,298.85,298.85,298.85,1006,18,3.80,321
8,8,Washington,Clouds,10000,292.21,292.21,292.21,1008,37,3.24,322
9,9,Washington,Clouds,10000,284.92,284.92,284.92,1010,59,3.08,276
10,10,Washington,Clouds,10000,282.75,282.75,282.75,1011,70,2.70,275
11,11,Washington,Clouds,10000,282.21,282.21,282.21,1010,70,2.18,271
12,12,Washington,Clear,10000,287.62,287.62,287.62,1010,49,2.52,284
13,13,Washington,Clouds,10000,290.03,290.03,290.03,1009,34,3.65,282
14,14,Washington,Clear,10000,291.51,291.51,291.51,1009,30,4.19,288
15,15,Washington,Clear,10000,289.02,289.02,289.02,1009,43,4.95,287
16,16,Washington,Clouds,10000,284.20,284.20,284.20,1011,65,2.99,289
17,17,Washington,Clouds,10000,279.72,279.72,279.72,1013,90,2.33,309
18,18,Washington,Clouds,10000,277.76,277.76,277.76,1015,92,2.55,286
19,19,Washington,Clouds,10000,276.82,276.82,276.82,1015,90,2.53,289
20,20,Washington,Clouds,10000,283.42,283.42,283.42,1014,54,2.00,338
21,21,Washington,Clouds,10000,288.51,288.51,288.51,1010,32,2.31,36
22,22,Washington,Clouds,10000,292.60,292.60,292.60,1006,22,1.61,186
23,23,Washington,Clouds,10000,289.29,289.29,289.29,1007,35,3.15,297
24,24,Washington,Clear,10000,286.79,286.79,286.79,1006,43,1.81,312
25,25,Washington,Clear,10000,278.93,278.93,278.93,1010,78,2.63,285
26,26,Washington,Clouds,10000,279.37,279.37,279.37,1011,70,2.57,298
27,27,Washington,Clouds,10000,276.07,276.07,276.07,1014,76,2.66,278
28,28,Washington,Clear,10000,282.94,282.94,282.94,1014,45,2.31,329
29,29,Washington,Clouds,10000,288.68,288.68,288.68,1011,30,1.96,81
30,30,Washington,Clouds,10000,291.51,291.51,291.51,1010,27,4.11,92
31,31,Washington,Clouds,10000,291.83,291.83,291.83,1008,27,3.37,107
32,32,Washington,Clouds,10000,288.60,288.60,288.60,1008,36,0.51,168
33,33,Washington,Clouds,10000,285.62,285.62,285.62,1008,40,1.90,274
34,34,Washington,Clouds,10000,284.58,284.58,284.58,1008,44,0.97,267
35,35,Washington,Rain,10000,283.75,283.75,283.75,1008,58,2.49,278
36,36,Washington,Rain,10000,283.48,283.48,283.48,1011,79,2.39,306
37,37,Washington,Rain,10000,287.04,287.04,287.04,1012,56,2.62,283
38,38,Washington,Rain,10000,291.51,291.51,291.51,1011,29,4.47,327
39,39,Washington,Clouds,10000,292.16,292.16,292.16,1012,26,2.70,305

In [47]:
#Save to csv
#df_predictions_wash.to_csv("wash.csv", index=False)

### Paris

In [48]:
# URL for Current Weather API
forecast_weather_url = 'http://api.openweathermap.org/data/2.5/forecast?'

In [49]:
# need to be replaced by your real API key
your_api_key = "277a72f5a19ff756ca573d7eaf5e56d9"
# Input `q` is the city name
city = "Paris"
# Input `appid` is your API KEY, 
appid = your_api_key
# Input `units` are preferred units such as Metric or Imperial
units = "&units=metric"
#current_query <- list(q = "Seoul", appid = your_api_key, units="metric")

In [50]:
forecast_response_json = requests.get(forecast_weather_url+"q="+city+"&appid="+appid).json()

In [51]:
forecast_response_json

{'cod': '200',
 'message': 0,
 'cnt': 40,
 'list': [{'dt': 1622775600,
   'main': {'temp': 290.42,
    'feels_like': 290.55,
    'temp_min': 288.56,
    'temp_max': 290.42,
    'pressure': 1020,
    'sea_level': 1020,
    'grnd_level': 1016,
    'humidity': 90,
    'temp_kf': 1.86},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 75},
   'wind': {'speed': 2.36, 'deg': 314, 'gust': 4.01},
   'visibility': 10000,
   'pop': 0.97,
   'rain': {'3h': 2.26},
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-04 03:00:00'},
  {'dt': 1622786400,
   'main': {'temp': 289.74,
    'feels_like': 289.86,
    'temp_min': 288.39,
    'temp_max': 289.74,
    'pressure': 1020,
    'sea_level': 1020,
    'grnd_level': 1016,
    'humidity': 92,
    'temp_kf': 1.35},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 83},
   'wind': {'speed': 2.5, 'deg': 357, 'gust': 5.52},
   'visibility': 10000,
   'pop': 1,
   'rain': {'3h': 0.93},
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-04 06:00:00'},
  {'dt': 1622797200,
   'main': {'temp': 290.96,
    'feels_like': 291.07,
    'temp_min': 290.96,
    'temp_max': 291.23,
    'pressure': 1021,
    'sea_level': 1021,
    'grnd_level': 1017,
    'humidity': 87,
    'temp_kf': -0.27},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 92},
   'wind': {'speed': 1.98, 'deg': 29, 'gust': 3.18},
   'visibility': 10000,
   'pop': 0.48,
   'rain': {'3h': 0.44},
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-04 09:00:00'},
  {'dt': 1622808000,
   'main': {'temp': 295.09,
    'feels_like': 295.06,
    'temp_min': 295.09,
    'temp_max': 295.09,
    'pressure': 1021,
    'sea_level': 1021,
    'grnd_level': 1017,
    'humidity': 66,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.43, 'deg': 324, 'gust': 1.15},
   'visibility': 10000,
   'pop': 0.4,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-04 12:00:00'},
  {'dt': 1622818800,
   'main': {'temp': 292.32,
    'feels_like': 292.56,
    'temp_min': 292.32,
    'temp_max': 292.32,
    'pressure': 1021,
    'sea_level': 1021,
    'grnd_level': 1016,
    'humidity': 87,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 3.18, 'deg': 324, 'gust': 4.69},
   'visibility': 9445,
   'pop': 0.86,
   'rain': {'3h': 1.5},
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-04 15:00:00'},
  {'dt': 1622829600,
   'main': {'temp': 289.92,
    'feels_like': 290.19,
    'temp_min': 289.92,
    'temp_max': 289.92,
    'pressure': 1021,
    'sea_level': 1021,
    'grnd_level': 1016,
    'humidity': 97,
    'temp_kf': 0},
   'weather': [{'id': 501,
     'main': 'Rain',
     'description': 'moderate rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 3.23, 'deg': 331, 'gust': 7.44},
   'visibility': 8117,
   'pop': 1,
   'rain': {'3h': 7.9},
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-04 18:00:00'},
  {'dt': 1622840400,
   'main': {'temp': 289.22,
    'feels_like': 289.42,
    'temp_min': 289.22,
    'temp_max': 289.22,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1017,
    'humidity': 97,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 3.63, 'deg': 319, 'gust': 7.5},
   'visibility': 10000,
   'pop': 0.79,
   'rain': {'3h': 1.35},
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-04 21:00:00'},
  {'dt': 1622851200,
   'main': {'temp': 287.8,
    'feels_like': 287.85,
    'temp_min': 287.8,
    'temp_max': 287.8,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1017,
    'humidity': 97,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 4.01, 'deg': 315, 'gust': 9.14},
   'visibility': 10000,
   'pop': 0.8,
   'rain': {'3h': 0.23},
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-05 00:00:00'},
  {'dt': 1622862000,
   'main': {'temp': 287.48,
    'feels_like': 287.5,
    'temp_min': 287.48,
    'temp_max': 287.48,
    'pressure': 1021,
    'sea_level': 1021,
    'grnd_level': 1017,
    'humidity': 97,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 4.14, 'deg': 326, 'gust': 9.89},
   'visibility': 10000,
   'pop': 0.48,
   'rain': {'3h': 0.8},
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-05 03:00:00'},
  {'dt': 1622872800,
   'main': {'temp': 286.77,
    'feels_like': 286.72,
    'temp_min': 286.77,
    'temp_max': 286.77,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1018,
    'humidity': 97,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 4.85, 'deg': 309, 'gust': 10.55},
   'visibility': 10000,
   'pop': 0.56,
   'rain': {'3h': 0.79},
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-05 06:00:00'},
  {'dt': 1622883600,
   'main': {'temp': 287.04,
    'feels_like': 286.91,
    'temp_min': 287.04,
    'temp_max': 287.04,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1019,
    'humidity': 93,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 4.33, 'deg': 313, 'gust': 10.06},
   'visibility': 10000,
   'pop': 0.46,
   'rain': {'3h': 0.51},
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-05 09:00:00'},
  {'dt': 1622894400,
   'main': {'temp': 288.91,
    'feels_like': 288.79,
    'temp_min': 288.91,
    'temp_max': 288.91,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1020,
    'humidity': 86,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 4.21, 'deg': 318, 'gust': 7.23},
   'visibility': 10000,
   'pop': 0.4,
   'rain': {'3h': 0.18},
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-05 12:00:00'},
  {'dt': 1622905200,
   'main': {'temp': 291.5,
    'feels_like': 291.3,
    'temp_min': 291.5,
    'temp_max': 291.5,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1020,
    'humidity': 73,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 3.93, 'deg': 336, 'gust': 5.94},
   'visibility': 10000,
   'pop': 0.2,
   'rain': {'3h': 0.1},
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-05 15:00:00'},
  {'dt': 1622916000,
   'main': {'temp': 291.15,
    'feels_like': 290.91,
    'temp_min': 291.15,
    'temp_max': 291.15,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1020,
    'humidity': 73,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 97},
   'wind': {'speed': 3.34, 'deg': 328, 'gust': 5.9},
   'visibility': 10000,
   'pop': 0.22,
   'rain': {'3h': 0.15},
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-05 18:00:00'},
  {'dt': 1622926800,
   'main': {'temp': 287.57,
    'feels_like': 287.23,
    'temp_min': 287.57,
    'temp_max': 287.57,
    'pressure': 1027,
    'sea_level': 1027,
    'grnd_level': 1022,
    'humidity': 83,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 20},
   'wind': {'speed': 2.39, 'deg': 331, 'gust': 6.73},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-05 21:00:00'},
  {'dt': 1622937600,
   'main': {'temp': 285.71,
    'feels_like': 285.14,
    'temp_min': 285.71,
    'temp_max': 285.71,
    'pressure': 1027,
    'sea_level': 1027,
    'grnd_level': 1022,
    'humidity': 81,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 13},
   'wind': {'speed': 2.01, 'deg': 326, 'gust': 5.15},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-06 00:00:00'},
  {'dt': 1622948400,
   'main': {'temp': 284.31,
    'feels_like': 283.49,
    'temp_min': 284.31,
    'temp_max': 284.31,
    'pressure': 1026,
    'sea_level': 1026,
    'grnd_level': 1021,
    'humidity': 77,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 13},
   'wind': {'speed': 1.69, 'deg': 332, 'gust': 3.31},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-06 03:00:00'},
  {'dt': 1622959200,
   'main': {'temp': 286.37,
    'feels_like': 285.55,
    'temp_min': 286.37,
    'temp_max': 286.37,
    'pressure': 1027,
    'sea_level': 1027,
    'grnd_level': 1022,
    'humidity': 69,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 7},
   'wind': {'speed': 1.85, 'deg': 336, 'gust': 3.16},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-06 06:00:00'},
  {'dt': 1622970000,
   'main': {'temp': 291.71,
    'feels_like': 291.19,
    'temp_min': 291.71,
    'temp_max': 291.71,
    'pressure': 1026,
    'sea_level': 1026,
    'grnd_level': 1021,
    'humidity': 60,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 0},
   'wind': {'speed': 2.37, 'deg': 347, 'gust': 3.3},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-06 09:00:00'},
  {'dt': 1622980800,
   'main': {'temp': 295.49,
    'feels_like': 294.98,
    'temp_min': 295.49,
    'temp_max': 295.49,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1021,
    'humidity': 46,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 1},
   'wind': {'speed': 2.43, 'deg': 357, 'gust': 3.11},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-06 12:00:00'},
  {'dt': 1622991600,
   'main': {'temp': 295.99,
    'feels_like': 295.56,
    'temp_min': 295.99,
    'temp_max': 295.99,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1020,
    'humidity': 47,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 34},
   'wind': {'speed': 3.8, 'deg': 358, 'gust': 3.6},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-06 15:00:00'},
  {'dt': 1623002400,
   'main': {'temp': 293.77,
    'feels_like': 293.43,
    'temp_min': 293.77,
    'temp_max': 293.77,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1020,
    'humidity': 59,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 50},
   'wind': {'speed': 3.14, 'deg': 29, 'gust': 4.38},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-06 18:00:00'},
  {'dt': 1623013200,
   'main': {'temp': 289.87,
    'feels_like': 289.58,
    'temp_min': 289.87,
    'temp_max': 289.87,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1020,
    'humidity': 76,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 1},
   'wind': {'speed': 1.85, 'deg': 14, 'gust': 3.67},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-06 21:00:00'},
  {'dt': 1623024000,
   'main': {'temp': 288.07,
    'feels_like': 287.89,
    'temp_min': 288.07,
    'temp_max': 288.07,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1020,
    'humidity': 87,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 1},
   'wind': {'speed': 1.99, 'deg': 8, 'gust': 5.66},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-07 00:00:00'},
  {'dt': 1623034800,
   'main': {'temp': 286.64,
    'feels_like': 286.39,
    'temp_min': 286.64,
    'temp_max': 286.64,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1020,
    'humidity': 90,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 0},
   'wind': {'speed': 1.62, 'deg': 18, 'gust': 3.28},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-07 03:00:00'},
  {'dt': 1623045600,
   'main': {'temp': 288.42,
    'feels_like': 287.91,
    'temp_min': 288.42,
    'temp_max': 288.42,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1020,
    'humidity': 73,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 0},
   'wind': {'speed': 1.81, 'deg': 28, 'gust': 2.88},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-07 06:00:00'},
  {'dt': 1623056400,
   'main': {'temp': 293.31,
    'feels_like': 292.82,
    'temp_min': 293.31,
    'temp_max': 293.31,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1019,
    'humidity': 55,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 0},
   'wind': {'speed': 2.13, 'deg': 13, 'gust': 2.62},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-07 09:00:00'},
  {'dt': 1623067200,
   'main': {'temp': 296.33,
    'feels_like': 295.88,
    'temp_min': 296.33,
    'temp_max': 296.33,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1018,
    'humidity': 45,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 4},
   'wind': {'speed': 2.78, 'deg': 16, 'gust': 2.79},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-07 12:00:00'},
  {'dt': 1623078000,
   'main': {'temp': 296.31,
    'feels_like': 295.88,
    'temp_min': 296.31,
    'temp_max': 296.31,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1018,
    'humidity': 46,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 95},
   'wind': {'speed': 2.84, 'deg': 25, 'gust': 2.79},
   'visibility': 10000,
   'pop': 0.15,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-07 15:00:00'},
  {'dt': 1623088800,
   'main': {'temp': 294.75,
    'feels_like': 294.45,
    'temp_min': 294.75,
    'temp_max': 294.75,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1018,
    'humidity': 57,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 97},
   'wind': {'speed': 2.32, 'deg': 19, 'gust': 3.31},
   'visibility': 10000,
   'pop': 0.24,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-07 18:00:00'},
  {'dt': 1623099600,
   'main': {'temp': 290.96,
    'feels_like': 290.75,
    'temp_min': 290.96,
    'temp_max': 290.96,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1019,
    'humidity': 75,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 99},
   'wind': {'speed': 1.93, 'deg': 2, 'gust': 4.18},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-07 21:00:00'},
  {'dt': 1623110400,
   'main': {'temp': 288.97,
    'feels_like': 288.8,
    'temp_min': 288.97,
    'temp_max': 288.97,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1019,
    'humidity': 84,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 96},
   'wind': {'speed': 2.16, 'deg': 356, 'gust': 5.57},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-08 00:00:00'},
  {'dt': 1623121200,
   'main': {'temp': 287.28,
    'feels_like': 286.92,
    'temp_min': 287.28,
    'temp_max': 287.28,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1019,
    'humidity': 83,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 35},
   'wind': {'speed': 2.14, 'deg': 349, 'gust': 5.14},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-08 03:00:00'},
  {'dt': 1623132000,
   'main': {'temp': 288.78,
    'feels_like': 288.28,
    'temp_min': 288.78,
    'temp_max': 288.78,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1019,
    'humidity': 72,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 19},
   'wind': {'speed': 2.37, 'deg': 357, 'gust': 4.04},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-08 06:00:00'},
  {'dt': 1623142800,
   'main': {'temp': 293.71,
    'feels_like': 293.31,
    'temp_min': 293.71,
    'temp_max': 293.71,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1019,
    'humidity': 57,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 38},
   'wind': {'speed': 2.46, 'deg': 357, 'gust': 2.96},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-08 09:00:00'},
  {'dt': 1623153600,
   'main': {'temp': 297.13,
    'feels_like': 296.78,
    'temp_min': 297.13,
    'temp_max': 297.13,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1018,
    'humidity': 46,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 36},
   'wind': {'speed': 2.7, 'deg': 349, 'gust': 2.69},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-08 12:00:00'},
  {'dt': 1623164400,
   'main': {'temp': 297.7,
    'feels_like': 297.36,
    'temp_min': 297.7,
    'temp_max': 297.7,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1017,
    'humidity': 44,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 68},
   'wind': {'speed': 3.33, 'deg': 353, 'gust': 2.93},
   'visibility': 10000,
   'pop': 0.05,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-08 15:00:00'},
  {'dt': 1623175200,
   'main': {'temp': 295.18,
    'feels_like': 294.98,
    'temp_min': 295.18,
    'temp_max': 295.18,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1017,
    'humidity': 59,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 84},
   'wind': {'speed': 3.56, 'deg': 6, 'gust': 4.38},
   'visibility': 10000,
   'pop': 0.06,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-08 18:00:00'},

In [52]:
df_predictions_paris = pd.DataFrame()

In [53]:
# Create empty lists to store the JSON Data
prediction_num = 0
list_prediction_num = []
city = []
weather = []
visibility = []
temp = []
temp_min = []
temp_max = []
pressure = []
humidity = []
wind_speed = []
wind_deg = []

In [54]:
for num_forecasts in forecast_response_json['list']:
    df_predictions_paris['prediction_num'] = prediction_num
    list_prediction_num.append(prediction_num)
    city.append(forecast_response_json['city']['name'])
    weather.append(forecast_response_json['list'][prediction_num]['weather'][0]['main'])
    visibility.append(forecast_response_json['list'][prediction_num]['visibility'])
    temp.append(forecast_response_json['list'][prediction_num]['main']['temp'])
    temp_min.append(forecast_response_json['list'][prediction_num]['main']['temp_min'])
    temp_max.append(forecast_response_json['list'][prediction_num]['main']['temp_max'])
    pressure.append(forecast_response_json['list'][prediction_num]['main']['pressure'])
    humidity.append(forecast_response_json['list'][prediction_num]['main']['humidity'])
    wind_speed.append(forecast_response_json['list'][prediction_num]['wind']['speed'])
    wind_deg.append(forecast_response_json['list'][prediction_num]['wind']['deg'])
    prediction_num += 1

Complete and call `get_weather_forecast_by_cities` function with a list of cities, and write the data frame into a csv file called `cities_weather_forecast.csv`

In [55]:
# Write Lists to DataFrame
df_predictions_paris['prediction_num'] = list_prediction_num
df_predictions_paris['city'] = city
df_predictions_paris['weather'] = weather
df_predictions_paris['visibility'] = visibility
df_predictions_paris['temperature'] = temp
df_predictions_paris['temperature_min'] = temp_min
df_predictions_paris['temperature_max'] = temp_max
df_predictions_paris['pressure'] = pressure
df_predictions_paris['humidity'] = humidity
df_predictions_paris['wind_speed'] = wind_speed
df_predictions_paris['wind_degree'] = wind_deg

In [56]:
df_predictions_paris

,prediction_num,city,weather,visibility,temperature,temperature_min,temperature_max,pressure,humidity,wind_speed,wind_degree
0,0,Paris,Rain,10000,290.42,288.56,290.42,1020,90,2.36,314
1,1,Paris,Rain,10000,289.74,288.39,289.74,1020,92,2.50,357
2,2,Paris,Rain,10000,290.96,290.96,291.23,1021,87,1.98,29
3,3,Paris,Clouds,10000,295.09,295.09,295.09,1021,66,1.43,324
4,4,Paris,Rain,9445,292.32,292.32,292.32,1021,87,3.18,324
5,5,Paris,Rain,8117,289.92,289.92,289.92,1021,97,3.23,331
6,6,Paris,Rain,10000,289.22,289.22,289.22,1022,97,3.63,319
7,7,Paris,Rain,10000,287.80,287.80,287.80,1022,97,4.01,315
8,8,Paris,Rain,10000,287.48,287.48,287.48,1021,97,4.14,326
9,9,Paris,Rain,10000,286.77,286.77,286.77,1023,97,4.85,309
10,10,Paris,Rain,10000,287.04,287.04,287.04,1024,93,4.33,313
11,11,Paris,Rain,10000,288.91,288.91,288.91,1025,86,4.21,318
12,12,Paris,Rain,10000,291.50,291.50,291.50,1025,73,3.93,336
13,13,Paris,Rain,10000,291.15,291.15,291.15,1025,73,3.34,328
14,14,Paris,Clouds,10000,287.57,287.57,287.57,1027,83,2.39,331
15,15,Paris,Clouds,10000,285.71,285.71,285.71,1027,81,2.01,326
16,16,Paris,Clouds,10000,284.31,284.31,284.31,1026,77,1.69,332
17,17,Paris,Clear,10000,286.37,286.37,286.37,1027,69,1.85,336
18,18,Paris,Clear,10000,291.71,291.71,291.71,1026,60,2.37,347
19,19,Paris,Clear,10000,295.49,295.49,295.49,1025,46,2.43,357
20,20,Paris,Clouds,10000,295.99,295.99,295.99,1024,47,3.80,358
21,21,Paris,Clouds,10000,293.77,293.77,293.77,1024,59,3.14,29
22,22,Paris,Clear,10000,289.87,289.87,289.87,1025,76,1.85,14
23,23,Paris,Clear,10000,288.07,288.07,288.07,1025,87,1.99,8
24,24,Paris,Clear,10000,286.64,286.64,286.64,1024,90,1.62,18
25,25,Paris,Clear,10000,288.42,288.42,288.42,1024,73,1.81,28
26,26,Paris,Clear,10000,293.31,293.31,293.31,1024,55,2.13,13
27,27,Paris,Clear,10000,296.33,296.33,296.33,1023,45,2.78,16
28,28,Paris,Clouds,10000,296.31,296.31,296.31,1022,46,2.84,25
29,29,Paris,Clouds,10000,294.75,294.75,294.75,1022,57,2.32,19
30,30,Paris,Clouds,10000,290.96,290.96,290.96,1023,75,1.93,2
31,31,Paris,Clouds,10000,288.97,288.97,288.97,1023,84,2.16,356
32,32,Paris,Clouds,10000,287.28,287.28,287.28,1023,83,2.14,349
33,33,Paris,Clouds,10000,288.78,288.78,288.78,1024,72,2.37,357
34,34,Paris,Clouds,10000,293.71,293.71,293.71,1024,57,2.46,357
35,35,Paris,Clouds,10000,297.13,297.13,297.13,1023,46,2.70,349
36,36,Paris,Clouds,10000,297.70,297.70,297.70,1022,44,3.33,353
37,37,Paris,Clouds,10000,295.18,295.18,295.18,1022,59,3.56,6
38,38,Paris,Clouds,10000,291.09,291.09,291.09,1023,75,2.60,9
39,39,Paris,Clouds,10000,289.00,289.00,289.00,1023,79,1.79,355

In [57]:
#Save to csv
#df_predictions_paris.to_csv("paris.csv", index=False)

### Suzhou

In [58]:
# URL for Current Weather API
forecast_weather_url = 'http://api.openweathermap.org/data/2.5/forecast?'

In [59]:
# need to be replaced by your real API key
your_api_key = "277a72f5a19ff756ca573d7eaf5e56d9"
# Input `q` is the city name
city = "Suzhou"
# Input `appid` is your API KEY, 
appid = your_api_key
# Input `units` are preferred units such as Metric or Imperial
units = "&units=metric"
#current_query <- list(q = "Seoul", appid = your_api_key, units="metric")

In [60]:
forecast_response_json = requests.get(forecast_weather_url+"q="+city+"&appid="+appid).json()

In [61]:
forecast_response_json

{'cod': '200',
 'message': 0,
 'cnt': 40,
 'list': [{'dt': 1622775600,
   'main': {'temp': 297,
    'feels_like': 296.93,
    'temp_min': 297,
    'temp_max': 297.23,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 1006,
    'humidity': 57,
    'temp_kf': -0.23},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 89},
   'wind': {'speed': 3.83, 'deg': 261, 'gust': 4.23},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-04 03:00:00'},
  {'dt': 1622786400,
   'main': {'temp': 297.78,
    'feels_like': 297.66,
    'temp_min': 297.78,
    'temp_max': 299.35,
    'pressure': 1007,
    'sea_level': 1007,
    'grnd_level': 1004,
    'humidity': 52,
    'temp_kf': -1.57},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 86},
   'wind': {'speed': 3.46, 'deg': 251, 'gust': 4.56},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-04 06:00:00'},
  {'dt': 1622797200,
   'main': {'temp': 298.83,
    'feels_like': 298.68,
    'temp_min': 298.83,
    'temp_max': 299.75,
    'pressure': 1006,
    'sea_level': 1006,
    'grnd_level': 1003,
    'humidity': 47,
    'temp_kf': -0.92},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 66},
   'wind': {'speed': 3.12, 'deg': 239, 'gust': 3.95},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-04 09:00:00'},
  {'dt': 1622808000,
   'main': {'temp': 295.6,
    'feels_like': 295.73,
    'temp_min': 295.6,
    'temp_max': 295.6,
    'pressure': 1006,
    'sea_level': 1006,
    'grnd_level': 1004,
    'humidity': 70,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 62},
   'wind': {'speed': 4.47, 'deg': 200, 'gust': 7.37},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-04 12:00:00'},
  {'dt': 1622818800,
   'main': {'temp': 294.1,
    'feels_like': 294.26,
    'temp_min': 294.1,
    'temp_max': 294.1,
    'pressure': 1006,
    'sea_level': 1006,
    'grnd_level': 1005,
    'humidity': 77,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 98},
   'wind': {'speed': 4.44, 'deg': 190, 'gust': 8.89},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-04 15:00:00'},
  {'dt': 1622829600,
   'main': {'temp': 293.29,
    'feels_like': 293.47,
    'temp_min': 293.29,
    'temp_max': 293.29,
    'pressure': 1005,
    'sea_level': 1005,
    'grnd_level': 1003,
    'humidity': 81,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 98},
   'wind': {'speed': 3.88, 'deg': 197, 'gust': 8.31},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-04 18:00:00'},
  {'dt': 1622840400,
   'main': {'temp': 292.44,
    'feels_like': 292.64,
    'temp_min': 292.44,
    'temp_max': 292.44,
    'pressure': 1005,
    'sea_level': 1005,
    'grnd_level': 1003,
    'humidity': 85,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 56},
   'wind': {'speed': 3.19, 'deg': 186, 'gust': 6.3},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-04 21:00:00'},
  {'dt': 1622851200,
   'main': {'temp': 296.58,
    'feels_like': 296.62,
    'temp_min': 296.58,
    'temp_max': 296.58,
    'pressure': 1006,
    'sea_level': 1006,
    'grnd_level': 1005,
    'humidity': 63,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 51},
   'wind': {'speed': 3.06, 'deg': 207, 'gust': 4.01},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-05 00:00:00'},
  {'dt': 1622862000,
   'main': {'temp': 301.12,
    'feels_like': 300.93,
    'temp_min': 301.12,
    'temp_max': 301.12,
    'pressure': 1005,
    'sea_level': 1005,
    'grnd_level': 1003,
    'humidity': 42,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 42},
   'wind': {'speed': 3.25, 'deg': 216, 'gust': 3.62},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-05 03:00:00'},
  {'dt': 1622872800,
   'main': {'temp': 303.41,
    'feels_like': 302.23,
    'temp_min': 303.41,
    'temp_max': 303.41,
    'pressure': 1003,
    'sea_level': 1003,
    'grnd_level': 1002,
    'humidity': 31,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 30},
   'wind': {'speed': 3.25, 'deg': 224, 'gust': 3.27},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-05 06:00:00'},
  {'dt': 1622883600,
   'main': {'temp': 303.12,
    'feels_like': 302.2,
    'temp_min': 303.12,
    'temp_max': 303.12,
    'pressure': 1003,
    'sea_level': 1003,
    'grnd_level': 1001,
    'humidity': 34,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 0},
   'wind': {'speed': 3.67, 'deg': 192, 'gust': 4.21},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-05 09:00:00'},
  {'dt': 1622894400,
   'main': {'temp': 297.57,
    'feels_like': 297.63,
    'temp_min': 297.57,
    'temp_max': 297.57,
    'pressure': 1004,
    'sea_level': 1004,
    'grnd_level': 1002,
    'humidity': 60,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 0},
   'wind': {'speed': 4.16, 'deg': 163, 'gust': 7.87},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-05 12:00:00'},
  {'dt': 1622905200,
   'main': {'temp': 295.31,
    'feels_like': 295.36,
    'temp_min': 295.31,
    'temp_max': 295.31,
    'pressure': 1005,
    'sea_level': 1005,
    'grnd_level': 1004,
    'humidity': 68,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 0},
   'wind': {'speed': 3.45, 'deg': 156, 'gust': 7.27},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-05 15:00:00'},
  {'dt': 1622916000,
   'main': {'temp': 294.51,
    'feels_like': 294.69,
    'temp_min': 294.51,
    'temp_max': 294.51,
    'pressure': 1005,
    'sea_level': 1005,
    'grnd_level': 1003,
    'humidity': 76,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 0},
   'wind': {'speed': 3.66, 'deg': 163, 'gust': 7.86},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-05 18:00:00'},
  {'dt': 1622926800,
   'main': {'temp': 293.84,
    'feels_like': 294,
    'temp_min': 293.84,
    'temp_max': 293.84,
    'pressure': 1006,
    'sea_level': 1006,
    'grnd_level': 1004,
    'humidity': 78,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 0},
   'wind': {'speed': 2.24, 'deg': 175, 'gust': 4.02},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-05 21:00:00'},
  {'dt': 1622937600,
   'main': {'temp': 298.53,
    'feels_like': 298.56,
    'temp_min': 298.53,
    'temp_max': 298.53,
    'pressure': 1006,
    'sea_level': 1006,
    'grnd_level': 1005,
    'humidity': 55,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 0},
   'wind': {'speed': 3.17, 'deg': 175, 'gust': 4.91},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-06 00:00:00'},
  {'dt': 1622948400,
   'main': {'temp': 303.85,
    'feels_like': 302.96,
    'temp_min': 303.85,
    'temp_max': 303.85,
    'pressure': 1006,
    'sea_level': 1006,
    'grnd_level': 1005,
    'humidity': 34,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 0},
   'wind': {'speed': 3.31, 'deg': 177, 'gust': 4.26},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-06 03:00:00'},
  {'dt': 1622959200,
   'main': {'temp': 306.2,
    'feels_like': 305.07,
    'temp_min': 306.2,
    'temp_max': 306.2,
    'pressure': 1005,
    'sea_level': 1005,
    'grnd_level': 1004,
    'humidity': 29,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 0},
   'wind': {'speed': 3.58, 'deg': 168, 'gust': 4.6},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-06 06:00:00'},
  {'dt': 1622970000,
   'main': {'temp': 304.56,
    'feels_like': 303.53,
    'temp_min': 304.56,
    'temp_max': 304.56,
    'pressure': 1005,
    'sea_level': 1005,
    'grnd_level': 1004,
    'humidity': 32,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 13},
   'wind': {'speed': 5.64, 'deg': 156, 'gust': 6.75},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-06 09:00:00'},
  {'dt': 1622980800,
   'main': {'temp': 297.76,
    'feels_like': 297.56,
    'temp_min': 297.76,
    'temp_max': 297.76,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 1006,
    'humidity': 49,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 7},
   'wind': {'speed': 4.74, 'deg': 134, 'gust': 10.18},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-06 12:00:00'},
  {'dt': 1622991600,
   'main': {'temp': 295.84,
    'feels_like': 295.52,
    'temp_min': 295.84,
    'temp_max': 295.84,
    'pressure': 1009,
    'sea_level': 1009,
    'grnd_level': 1007,
    'humidity': 52,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 88},
   'wind': {'speed': 4.3, 'deg': 130, 'gust': 10.55},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-06 15:00:00'},
  {'dt': 1623002400,
   'main': {'temp': 294.6,
    'feels_like': 294.29,
    'temp_min': 294.6,
    'temp_max': 294.6,
    'pressure': 1009,
    'sea_level': 1009,
    'grnd_level': 1007,
    'humidity': 57,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 91},
   'wind': {'speed': 3.6, 'deg': 130, 'gust': 8.57},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-06 18:00:00'},
  {'dt': 1623013200,
   'main': {'temp': 293.94,
    'feels_like': 293.64,
    'temp_min': 293.94,
    'temp_max': 293.94,
    'pressure': 1009,
    'sea_level': 1009,
    'grnd_level': 1008,
    'humidity': 60,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 3.72, 'deg': 134, 'gust': 8.62},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-06 21:00:00'},
  {'dt': 1623024000,
   'main': {'temp': 298.49,
    'feels_like': 298.31,
    'temp_min': 298.49,
    'temp_max': 298.49,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 1008,
    'humidity': 47,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 99},
   'wind': {'speed': 4.65, 'deg': 146, 'gust': 8.04},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-07 00:00:00'},
  {'dt': 1623034800,
   'main': {'temp': 302.84,
    'feels_like': 302.19,
    'temp_min': 302.84,
    'temp_max': 302.84,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 1008,
    'humidity': 37,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 84},
   'wind': {'speed': 5.35, 'deg': 143, 'gust': 7.89},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-07 03:00:00'},
  {'dt': 1623045600,
   'main': {'temp': 304.48,
    'feels_like': 303.55,
    'temp_min': 304.48,
    'temp_max': 304.48,
    'pressure': 1009,
    'sea_level': 1009,
    'grnd_level': 1007,
    'humidity': 33,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 92},
   'wind': {'speed': 5.97, 'deg': 136, 'gust': 8.49},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-07 06:00:00'},
  {'dt': 1623056400,
   'main': {'temp': 301.41,
    'feels_like': 301.9,
    'temp_min': 301.41,
    'temp_max': 301.41,
    'pressure': 1009,
    'sea_level': 1009,
    'grnd_level': 1007,
    'humidity': 50,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 5.86, 'deg': 129, 'gust': 9},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-07 09:00:00'},
  {'dt': 1623067200,
   'main': {'temp': 298.11,
    'feels_like': 298.54,
    'temp_min': 298.11,
    'temp_max': 298.11,
    'pressure': 1009,
    'sea_level': 1009,
    'grnd_level': 1007,
    'humidity': 72,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 5.29, 'deg': 121, 'gust': 10.89},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-07 12:00:00'},
  {'dt': 1623078000,
   'main': {'temp': 297.49,
    'feels_like': 298.07,
    'temp_min': 297.49,
    'temp_max': 297.49,
    'pressure': 1009,
    'sea_level': 1009,
    'grnd_level': 1007,
    'humidity': 80,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 4.71, 'deg': 113, 'gust': 10.76},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-07 15:00:00'},
  {'dt': 1623088800,
   'main': {'temp': 296.61,
    'feels_like': 297.26,
    'temp_min': 296.61,
    'temp_max': 296.61,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 1007,
    'humidity': 86,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 3.66, 'deg': 115, 'gust': 6.53},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-07 18:00:00'},
  {'dt': 1623099600,
   'main': {'temp': 296.78,
    'feels_like': 297.31,
    'temp_min': 296.78,
    'temp_max': 296.78,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 1007,
    'humidity': 81,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.69, 'deg': 110, 'gust': 4.74},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-07 21:00:00'},
  {'dt': 1623110400,
   'main': {'temp': 297.54,
    'feels_like': 298.2,
    'temp_min': 297.54,
    'temp_max': 297.54,
    'pressure': 1009,
    'sea_level': 1009,
    'grnd_level': 1007,
    'humidity': 83,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 3.28, 'deg': 82, 'gust': 4.88},
   'visibility': 10000,
   'pop': 0.02,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-08 00:00:00'},
  {'dt': 1623121200,
   'main': {'temp': 298.97,
    'feels_like': 299.67,
    'temp_min': 298.97,
    'temp_max': 298.97,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 1007,
    'humidity': 79,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 99},
   'wind': {'speed': 4.35, 'deg': 98, 'gust': 6.31},
   'visibility': 10000,
   'pop': 0.28,
   'rain': {'3h': 0.21},
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-08 03:00:00'},
  {'dt': 1623132000,
   'main': {'temp': 300.29,
    'feels_like': 302.43,
    'temp_min': 300.29,
    'temp_max': 300.29,
    'pressure': 1007,
    'sea_level': 1007,
    'grnd_level': 1006,
    'humidity': 72,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 99},
   'wind': {'speed': 3.63, 'deg': 99, 'gust': 5.31},
   'visibility': 10000,
   'pop': 0.35,
   'rain': {'3h': 0.17},
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-08 06:00:00'},
  {'dt': 1623142800,
   'main': {'temp': 300.98,
    'feels_like': 303.25,
    'temp_min': 300.98,
    'temp_max': 300.98,
    'pressure': 1007,
    'sea_level': 1007,
    'grnd_level': 1005,
    'humidity': 68,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 96},
   'wind': {'speed': 3.87, 'deg': 72, 'gust': 5.04},
   'visibility': 10000,
   'pop': 0.36,
   'rain': {'3h': 0.12},
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-08 09:00:00'},
  {'dt': 1623153600,
   'main': {'temp': 298.14,
    'feels_like': 298.81,
    'temp_min': 298.14,
    'temp_max': 298.14,
    'pressure': 1007,
    'sea_level': 1007,
    'grnd_level': 1006,
    'humidity': 81,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 80},
   'wind': {'speed': 4.68, 'deg': 94, 'gust': 7.85},
   'visibility': 10000,
   'pop': 0.31,
   'rain': {'3h': 0.12},
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-08 12:00:00'},
  {'dt': 1623164400,
   'main': {'temp': 296.98,
    'feels_like': 297.61,
    'temp_min': 296.98,
    'temp_max': 296.98,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 1007,
    'humidity': 84,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 83},
   'wind': {'speed': 3.44, 'deg': 96, 'gust': 6},
   'visibility': 10000,
   'pop': 0.02,
   'sys': {'pod': 'n'},
   'dt_txt': '2021-06-08 15:00:00'},
  {'dt': 1623175200,
   'main': {'temp': 296.42,
    'feels_like': 297.02,
    'temp_min': 296.42,
    'temp_max': 296.42,
    'pressure': 1007,
    'sea_level': 1007,
    'grnd_level': 1006,
    'humidity': 85,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 92},
   'wind': {'speed': 3.26, 'deg': 72, 'gust': 5.24},
   'visibility': 10000,
   'pop': 0.02,
   'sys': {'pod': 'd'},
   'dt_txt': '2021-06-08 18:00:00'},
  {'dt': 1623186000,
   'main': {'temp': 295.62,
    'feels_like': 296.22,
    'temp_min': 295.62,
    'temp_max': 295.62,
    'pressure': 1007,
    'sea_level': 1007,
    'grnd_level': 1006,

In [62]:
df_predictions_suzhou = pd.DataFrame()

In [63]:
# Create empty lists to store the JSON Data
prediction_num = 0
list_prediction_num = []
city = []
weather = []
visibility = []
temp = []
temp_min = []
temp_max = []
pressure = []
humidity = []
wind_speed = []
wind_deg = []

In [64]:
for num_forecasts in forecast_response_json['list']:
    df_predictions_suzhou['prediction_num'] = prediction_num
    list_prediction_num.append(prediction_num)
    city.append(forecast_response_json['city']['name'])
    weather.append(forecast_response_json['list'][prediction_num]['weather'][0]['main'])
    visibility.append(forecast_response_json['list'][prediction_num]['visibility'])
    temp.append(forecast_response_json['list'][prediction_num]['main']['temp'])
    temp_min.append(forecast_response_json['list'][prediction_num]['main']['temp_min'])
    temp_max.append(forecast_response_json['list'][prediction_num]['main']['temp_max'])
    pressure.append(forecast_response_json['list'][prediction_num]['main']['pressure'])
    humidity.append(forecast_response_json['list'][prediction_num]['main']['humidity'])
    wind_speed.append(forecast_response_json['list'][prediction_num]['wind']['speed'])
    wind_deg.append(forecast_response_json['list'][prediction_num]['wind']['deg'])
    prediction_num += 1

Complete and call `get_weather_forecast_by_cities` function with a list of cities, and write the data frame into a csv file called `cities_weather_forecast.csv`

In [65]:
# Write Lists to DataFrame
df_predictions_suzhou['prediction_num'] = list_prediction_num
df_predictions_suzhou['city'] = city
df_predictions_suzhou['weather'] = weather
df_predictions_suzhou['visibility'] = visibility
df_predictions_suzhou['temperature'] = temp
df_predictions_suzhou['temperature_min'] = temp_min
df_predictions_suzhou['temperature_max'] = temp_max
df_predictions_suzhou['pressure'] = pressure
df_predictions_suzhou['humidity'] = humidity
df_predictions_suzhou['wind_speed'] = wind_speed
df_predictions_suzhou['wind_degree'] = wind_deg

In [66]:
df_predictions_suzhou

,prediction_num,city,weather,visibility,temperature,temperature_min,temperature_max,pressure,humidity,wind_speed,wind_degree
0,0,Suzhou,Clouds,10000,297.00,297.00,297.23,1008,57,3.83,261
1,1,Suzhou,Clouds,10000,297.78,297.78,299.35,1007,52,3.46,251
2,2,Suzhou,Clouds,10000,298.83,298.83,299.75,1006,47,3.12,239
3,3,Suzhou,Clouds,10000,295.60,295.60,295.60,1006,70,4.47,200
4,4,Suzhou,Clouds,10000,294.10,294.10,294.10,1006,77,4.44,190
5,5,Suzhou,Clouds,10000,293.29,293.29,293.29,1005,81,3.88,197
6,6,Suzhou,Clouds,10000,292.44,292.44,292.44,1005,85,3.19,186
7,7,Suzhou,Clouds,10000,296.58,296.58,296.58,1006,63,3.06,207
8,8,Suzhou,Clouds,10000,301.12,301.12,301.12,1005,42,3.25,216
9,9,Suzhou,Clouds,10000,303.41,303.41,303.41,1003,31,3.25,224
10,10,Suzhou,Clear,10000,303.12,303.12,303.12,1003,34,3.67,192
11,11,Suzhou,Clear,10000,297.57,297.57,297.57,1004,60,4.16,163
12,12,Suzhou,Clear,10000,295.31,295.31,295.31,1005,68,3.45,156
13,13,Suzhou,Clear,10000,294.51,294.51,294.51,1005,76,3.66,163
14,14,Suzhou,Clear,10000,293.84,293.84,293.84,1006,78,2.24,175
15,15,Suzhou,Clear,10000,298.53,298.53,298.53,1006,55,3.17,175
16,16,Suzhou,Clear,10000,303.85,303.85,303.85,1006,34,3.31,177
17,17,Suzhou,Clear,10000,306.20,306.20,306.20,1005,29,3.58,168
18,18,Suzhou,Clouds,10000,304.56,304.56,304.56,1005,32,5.64,156
19,19,Suzhou,Clear,10000,297.76,297.76,297.76,1008,49,4.74,134
20,20,Suzhou,Clouds,10000,295.84,295.84,295.84,1009,52,4.30,130
21,21,Suzhou,Clouds,10000,294.60,294.60,294.60,1009,57,3.60,130
22,22,Suzhou,Clouds,10000,293.94,293.94,293.94,1009,60,3.72,134
23,23,Suzhou,Clouds,10000,298.49,298.49,298.49,1010,47,4.65,146
24,24,Suzhou,Clouds,10000,302.84,302.84,302.84,1010,37,5.35,143
25,25,Suzhou,Clouds,10000,304.48,304.48,304.48,1009,33,5.97,136
26,26,Suzhou,Clouds,10000,301.41,301.41,301.41,1009,50,5.86,129
27,27,Suzhou,Clouds,10000,298.11,298.11,298.11,1009,72,5.29,121
28,28,Suzhou,Clouds,10000,297.49,297.49,297.49,1009,80,4.71,113
29,29,Suzhou,Clouds,10000,296.61,296.61,296.61,1008,86,3.66,115
30,30,Suzhou,Clouds,10000,296.78,296.78,296.78,1008,81,2.69,110
31,31,Suzhou,Clouds,10000,297.54,297.54,297.54,1009,83,3.28,82
32,32,Suzhou,Rain,10000,298.97,298.97,298.97,1008,79,4.35,98
33,33,Suzhou,Rain,10000,300.29,300.29,300.29,1007,72,3.63,99
34,34,Suzhou,Rain,10000,300.98,300.98,300.98,1007,68,3.87,72
35,35,Suzhou,Rain,10000,298.14,298.14,298.14,1007,81,4.68,94
36,36,Suzhou,Clouds,10000,296.98,296.98,296.98,1008,84,3.44,96
37,37,Suzhou,Clouds,10000,296.42,296.42,296.42,1007,85,3.26,72
38,38,Suzhou,Rain,10000,295.62,295.62,295.62,1007,88,4.21,60
39,39,Suzhou,Clouds,10000,295.58,295.58,295.58,1008,87,4.41,58

In [67]:
#Save to csv
#df_predictions_suzhou.to_csv("suzhou.csv", index=False)

In [68]:
# cities <- c("Seoul", "Washington, D.C.", "Paris", "Suzhou")
# cities_weather_df <- get_weather_forecast_by_cities(cities)

### Combine all 4 files and save As

In [69]:
# Write cities_weather_df to `cities_weather_forecast.csv`
#write.csv(cities_weather_df, "cities_weather_forecast.csv", row.names=FALSE)

In [70]:
seoul = pd.read_csv("seoul.csv")
wash = pd.read_csv("wash.csv")
paris = pd.read_csv("paris.csv")
suzhou = pd.read_csv("suzhou.csv")

In [71]:
seoul.head()

,prediction_num,city,weather,visibility,temperature,temperature_min,temperature_max,pressure,humidity,wind_speed,wind_degree
0,0,Seoul,Clouds,10000,296.03,295.48,296.03,1014,61,2.02,131
1,1,Seoul,Clouds,10000,295.20,293.55,295.20,1014,59,0.72,39
2,2,Seoul,Clouds,10000,293.40,292.08,293.40,1014,63,0.36,18
3,3,Seoul,Clouds,10000,290.76,290.76,290.76,1014,68,1.12,88
4,4,Seoul,Clouds,10000,290.34,290.34,290.34,1015,70,1.46,66

In [72]:
wash.head()

,prediction_num,city,weather,visibility,temperature,temperature_min,temperature_max,pressure,humidity,wind_speed,wind_degree
0,0,Washington,Clouds,10000,290.90,288.90,290.90,1019,56,2.15,296
1,1,Washington,Clouds,10000,290.01,288.22,290.01,1019,60,1.77,295
2,2,Washington,Clouds,10000,293.29,293.29,294.48,1018,50,1.13,352
3,3,Washington,Clouds,10000,301.60,301.60,301.60,1015,29,1.69,89
4,4,Washington,Clear,10000,305.14,305.14,305.14,1012,24,2.90,99

In [73]:
paris.head()

,prediction_num,city,weather,visibility,temperature,temperature_min,temperature_max,pressure,humidity,wind_speed,wind_degree
0,0,Paris,Clear,10000,296.54,296.54,298.21,1012,47,4.31,101
1,1,Paris,Clear,10000,298.12,298.12,299.32,1011,47,4.26,100
2,2,Paris,Clear,10000,296.70,296.70,296.70,1011,62,4.43,85
3,3,Paris,Rain,10000,292.07,292.07,292.07,1012,85,3.36,75
4,4,Paris,Rain,10000,289.64,289.64,289.64,1012,91,1.99,83

In [74]:
suzhou.head()

,prediction_num,city,weather,visibility,temperature,temperature_min,temperature_max,pressure,humidity,wind_speed,wind_degree
0,0,Suzhou,Clouds,10000,298.16,296.05,298.16,1007,78,7.31,131
1,1,Suzhou,Rain,10000,296.49,295.12,296.49,1008,82,7.74,129
2,2,Suzhou,Rain,10000,295.05,295.05,295.05,1007,87,7.00,125
3,3,Suzhou,Rain,10000,294.86,294.86,294.86,1007,90,6.56,123
4,4,Suzhou,Rain,10000,295.34,295.34,295.34,1007,91,5.58,125

In [75]:
cities_weather_df = pd.concat([seoul,wash,paris,suzhou], axis=0)

In [76]:
cities_weather_df

,prediction_num,city,weather,visibility,temperature,temperature_min,temperature_max,pressure,humidity,wind_speed,wind_degree
0,0,Seoul,Clouds,10000,296.03,295.48,296.03,1014,61,2.02,131
1,1,Seoul,Clouds,10000,295.20,293.55,295.20,1014,59,0.72,39
2,2,Seoul,Clouds,10000,293.40,292.08,293.40,1014,63,0.36,18
3,3,Seoul,Clouds,10000,290.76,290.76,290.76,1014,68,1.12,88
4,4,Seoul,Clouds,10000,290.34,290.34,290.34,1015,70,1.46,66
5,5,Seoul,Clouds,10000,296.28,296.28,296.28,1014,48,1.02,88
6,6,Seoul,Clouds,10000,301.19,301.19,301.19,1013,32,2.37,201
7,7,Seoul,Clouds,10000,302.45,302.45,302.45,1011,30,3.90,233
8,8,Seoul,Clouds,10000,299.66,299.66,299.66,1010,36,4.32,254
9,9,Seoul,Clouds,10000,295.92,295.92,295.92,1012,49,2.12,278
10,10,Seoul,Clouds,10000,294.95,294.95,294.95,1011,55,1.50,225
11,11,Seoul,Clouds,10000,293.15,293.15,293.15,1010,67,1.26,269
12,12,Seoul,Clouds,10000,292.45,292.45,292.45,1008,73,0.41,148
13,13,Seoul,Rain,10000,292.41,292.41,292.41,1007,77,0.97,234
14,14,Seoul,Rain,6620,290.68,290.68,290.68,1006,92,2.18,255
15,15,Seoul,Rain,9948,290.74,290.74,290.74,1004,91,0.70,325
16,16,Seoul,Rain,10000,290.71,290.71,290.71,1003,91,1.58,308
17,17,Seoul,Clouds,10000,289.69,289.69,289.69,1003,95,1.35,289
18,18,Seoul,Rain,10000,289.21,289.21,289.21,1003,85,3.80,320
19,19,Seoul,Clouds,10000,287.75,287.75,287.75,1002,88,1.18,308
20,20,Seoul,Clouds,10000,287.86,287.86,287.86,1003,83,0.62,187
21,21,Seoul,Clouds,10000,292.70,292.70,292.70,1002,58,1.57,211
22,22,Seoul,Clear,10000,296.43,296.43,296.43,1002,35,5.36,232
23,23,Seoul,Clear,10000,296.62,296.62,296.62,1001,30,6.88,237
24,24,Seoul,Clear,10000,294.48,294.48,294.48,1000,38,6.93,225
25,25,Seoul,Clear,10000,290.60,290.60,290.60,1001,66,5.00,240
26,26,Seoul,Clear,10000,289.34,289.34,289.34,1002,79,2.00,221
27,27,Seoul,Clear,10000,288.31,288.31,288.31,1001,86,1.65,192
28,28,Seoul,Clear,10000,288.03,288.03,288.03,1001,88,1.69,159
29,29,Seoul,Clear,10000,292.98,292.98,292.98,1002,56,2.93,200
30,30,Seoul,Clear,10000,297.67,297.67,297.67,1001,35,5.24,229
31,31,Seoul,Clear,10000,298.83,298.83,298.83,1000,31,5.68,235
32,32,Seoul,Clear,10000,296.69,296.69,296.69,1000,40,4.37,237
33,33,Seoul,Clouds,10000,293.77,293.77,293.77,1001,61,1.80,224
34,34,Seoul,Clouds,10000,291.97,291.97,291.97,1002,83,2.16,204
35,35,Seoul,Rain,10000,291.56,291.56,291.56,1002,84,2.95,194
36,36,Seoul,Rain,10000,290.79,290.79,290.79,1003,89,2.16,174
37,37,Seoul,Rain,10000,291.77,291.77,291.77,1004,84,2.28,181
38,38,Seoul,Clouds,10000,296.91,296.91,296.91,1005,58,3.27,207
39,39,Seoul,Clouds,10000,298.92,298.92,298.92,1004,47,4.30,242
0,0,Washington,Clouds,10000,290.90,288.90,290.90,1019,56,2.15,296
1,1,Washington,Clouds,10000,290.01,288.22,290.01,1019,60,1.77,295
2,2,Washington,Clouds,10000,293.29,293.29,294.48,1018,50,1.13,352
3,3,Washington,Clouds,10000,301.60,301.60,301.60,1015,29,1.69,89
4,4,Washington,Clear,10000,305.14,305.14,305.14,1012,24,2.90,99
5,5,Washington,Clear,10000,306.10,306.10,306.10,1010,23,3.37,104
6,6,Washington,Clear,10000,299.71,299.71,299.71,1010,42,0.70,65
7,7,Washington,Clear,10000,293.11,293.11,293.11,1011,55,2.43,283
8,8,Washington,Clear,10000,291.22,291.22,291.22,1011,60,2.10,293
9,9,Washington,Clear,10000,290.13,290.13,290.13,1011,54,2.06,294
10,10,Washington,Clear,10000,297.52,297.52,297.52,1011,35,1.42,350
11,11,Washington,Clear,10000,304.43,304.43,304.43,1009,20,1.70,77
12,12,Washington,Clear,10000,308.42,308.42,308.42,1006,15,1.62,117
13,13,Washington,Clear,10000,306.93,306.93,306.93,1005,17,3.64,340
14,14,Washington,Clear,10000,299.49,299.49,299.49,1006,35,2.71,325
15,15,Washington,Clear,10000,291.53,291.53,291.53,1009,58,3.01,285
16,16,Washington,Clear,10000,289.25,289.25,289.25,1009,67,2.79,286
17,17,Washington,Clear,10000,287.94,287.94,287.94,1009,66,2.65,289
18,18,Washington,Clear,10000,296.28,296.28,296.28,1009,37,2.24,318
19,19,Washington,Clear,10000,302.95,302.95,302.95,1007,18,2.58,354
20,20,Washington,Clear,10000,306.55,306.55,306.55,1006,16,1.80,329
21,21,Washington,Clear,10000,304.42,304.42,304.42,1004,20,3.48,340
22,22,Washington,Clear,10000,297.04,297.04,297.04,1006,42,2.91,327
23,23,Washington,Clouds,10000,289.60,289.60,289.60,1009,69,3.04,282
24,24,Washington,Clouds,10000,287.31,287.31,287.31,1009,79,2.68,282
25,25,Washington,Clouds,10000,285.73,285.73,285.73,1009,85,2.61,283
26,26,Washington,Clear,10000,292.89,292.89,292.89,1009,50,1.95,305
27,27,Washington,Clear,10000,299.76,299.76,299.76,1006,18,2.06,338
28,28,Washington,Clouds,10000,301.46,301.46,301.46,1005,10,2.67,277
29,29,Washington,Clouds,10000,298.06,298.06,298.06,1005,14,3.71,284
30,30,Washington,Clear,10000,291.07,291.07,291.07,1007,35,3.09,319
31,31,Washington,Clear,10000,283.66,283.66,283.66,1009,57,2.96,289
32,32,Washington,Clear,10000,281.23,281.23,281.23,1010,74,2.49,290
33,33,Washington,Clear,10000,279.99,279.99,279.99,1012,81,2.24,268
34,34,Washington,Rain,10000,284.37,284.37,284.37,1013,68,1.92,292
35,35,Washington,Rain,10000,288.96,288.96,288.96,1011,43,4.02,278
36,36,Washington,Clear,10000,291.35,291.35,291.35,1010,32,4.90,277
37,37,Washington,Clear,10000,290.10,290.10,290.10,1010,35,5.48,269
38,38,Washington,Clear,10000,286.05,286.05,286.05,1011,46,3.82,260
39,39,Washington,Clear,10000,278.54,278.54,278.54,1015,77,2.44,281
0,0,Paris,Clear,10000,296.54,296.54,298.21,1012,47,4.31,101
1,1,Paris,Clear,10000,298.12,298.12,299.32,1011,47,4.26,100
2,2,Paris,Clear,10000,296.70,296.70,296.70,1011,62,4.43,85
3,3,Paris,Rain,10000,292.07,292.07,292.07,1012,85,3.36,75
4,4,Paris,Rain,10000,289.64,289.64,289.64,1012,91,1.99,83
5,5,Paris,Clouds,10000,288.18,288.18,288.18,1011,89,2.14,85
6,6,Paris,Clouds,10000,289.69,289.69,289.69,1012,78,2.05,106
7,7,Paris,Clouds,10000,295.36,295.36,295.36,1013,61,2.13,166
8,8,Paris,Clouds,10000,297.16,297.16,297.16,1013,61,3.48,214
9,9,Paris,Rain,10000,297.49,297.49,297.49,1014,61,3.36,197
10,10,Paris,Rain,10000,296.08,296.08,296.08,1014,71,3.06,207
11,11,Paris,Rain,10000,292.54,292.54,292.54,1016,87,2.33,203
12,12,Paris,Rain,10000,290.97,290.97,290.97,1017,93,2.20,214
13,13,Paris,Rain,10000,289.73,289.73,289.73,1018,96,1.83,237
14,14,Paris,Rain,10000,291.10,291.10,291.10,1020,86,2.25,262
15,15,Paris,Clouds,10000,295.54,295.54,295.54,1021,57,2.54,264
16,16,Paris,Clouds,10000,298.53,298.53,298.53,1021,46,2.80,289
17,17,Paris,Clouds,10000,299.43,299.43,299.43,1020,45,2.39,331
18,18,Paris,Clouds,10000,297.41,297.41,297.41,1021,56,2.43,2
19,19,Paris,Clouds,10000,292.42,292.42,292.42,1023,81,2.92,24
20,20,Paris,Clouds,10000,290.05,290.05,290.05,1023,82,2.50,20
21,21,Paris,Clouds,10000,288.44,288.44,288.44,1023,82,2.05,26
22,22,Paris,Clouds,10000,289.62,289.62,289.62,1023,73,2.55,13
23,23,Paris,Clouds,10000,294.57,294.57,294.57,1023,63,2.61,48
24,24,Paris,Clouds,10000,298.66,298.66,298.66,1022,53,3.23,52
25,25,Paris,Rain,10000,298.89,298.89,298.89,1021,53,3.99,59
26,26,Paris,Rain,10000,293.80,293.80,293.80,1021,87,2.73,37
27,27,Paris,Rain,10000,292.60,292.60,292.60,1022,90,2.12,25
28,28,Paris,Clouds,10000,290.96,290.96,290.96,1021,95,3.44,22
29,29,Paris,Rain,10000,289.68,289.68,289.68,1020,97,2.84,24
30,30,Paris,Rain,10000,290.46,290.46,290.46,1019,94,3.98,30
31,31,Paris,Clouds,10000,296.66,296.66,296.66,1017,68,3.70,70
32,32,Paris,Rain,10000,299.22,299.22,299.22,1016,58,3.91,85
33,33,Paris,Rain,10000,296.50,296.50,296.50,1015,79,2.26,128
34,34,Paris,Rain,10000,293.94,293.94,293.94,1015,89,2.62,181
35,35,Paris,Rain,10000,291.19,291.19,291.19,1015,96,2.78,208
36,36,Paris,Rain,10000,290.47,290.47,290.47,1015,96,2.47,234
37,37,Paris,Rain,10000,289.98,289.98,289.98,1014,97,1.76,209
38,38,Paris,Rain,10000,290.05,290.05,290.05,1015,97,2.02,203
39,39,Paris,Rain,10000,290.32,290.32,290.32,1016,96,2.06,205
0,0,Suzhou,Clouds,10000,298.16,296.05,298.16,1007,78,7.31,131
1,1,Suzhou,Rain,10000,296.49,295.12,296.49,1008,82,7.74,129
2,2,Suzhou,Rain,10000,295.05,295.05,295.05,1007,87,7.00,125
3,3,Suzhou,Rain,10000,294.86,294.86,294.86,1007,90,6.56,123
4,4,Suzhou,Rain,10000,295.34,295.34,295.34,1007,91,5.58,125
5,5,Suzhou,Clouds,10000,297.51,297.51,297.51,1007,85,4.89,140
6,6,Suzhou,Clouds,10000,300.39,300.39,300.39,1004,75,3.10,138
7,7,Suzhou,Clouds,10000,300.94,300.94,300.94,1004,73,3.24,127
8,8,Suzhou,Clouds,10000,298.40,298.40,298.40,1004,86,3.14,120
9,9,Suzhou,Rain,10000,296.92,296.92,296.92,1005,93,2.06,123
10,10,Suzhou,Rain,10000,296.45,296.45,296.45,1003,95,0.99,160
11,11,Suzhou,Rain,10000,295.92,295.92,295.92,1003,97,0.68,307
12,12,Suzhou,Rain,10000,298.74,298.74,298.74,1004,82,3.14,356
13,13,Suzhou,Clouds,10000,300.97,300.97,300.97,1004,63,4.19,355
14,14,Suzhou,Clouds,10000,299.96,299.96,299.96,1003,63,1.82,326
15,15,Suzhou,Clouds,10000,298.53,298.53,298.53,1004,67,3.94,353
16,16,Suzhou,Clouds,10000,297.13,297.13,297.13,1006,72,1.10,16
17,17,Suzhou,Clouds,10000,296.52,296.52,296.52,1006,74,1.26,237
18,18,Suzhou,Clouds,10000,295.66,295.66,295.66,1005,80,1.14,359
19,19,Suzhou,Clouds,10000,295.01,295.01,295.01,1006,83,1.75,18
20,20,Suzhou,Clouds,10000,296.60,296.60,296.60,1006,76,0.64,114
21,21,Suzhou,Clouds,10000,299.52,299.52,299.52,1006,64,2.39,254
22,22,Suzhou,Clouds,10000,302.70,302.70,302.70,1004,42,2.48,272
23,23,Suzhou,Clouds,10000,302.63,302.63,302.63,1003,38,2.39,265
24,24,Suzhou,Clouds,10000,299.03,299.03,299.03,1005,52,0.68,359
25,25,Suzhou,Clouds,10000,296.84,296.84,296.84,1005,65,2.74,162
26,26,Suzhou,Clouds,10000,295.44,295.44,295.44,1004,77,2.81,189
27,27,Suzhou,Clouds,10000,294.46,294.46,294.46,1004,78,2.78,182
28,28,Suzhou,Clouds,10000,298.70,298.70,298.70,1004,57,3.46,196
29,29,Suzhou,Clouds,10000,303.21,303.21,303.21,1004,37,4.03,213
30,30,Suzhou,Clouds,10000,305.20,305.20,305.20,1002,29,3.63,225
31,31,Suzhou,Clouds,10000,304.81,304.81,304.81,1001,32,3.74,189
32,32,Suzhou,Clouds,10000,299.14,299.14,299.14,1002,54,4.34,158
33,33,Suzhou,Clouds,10000,297.33,297.33,297.33,1003,65,4.90,158
34,34,Suzhou,Clouds,10000,296.53,296.53,296.53,1002,68,3.55,166
35,35,Suzhou,Clouds,10000,295.43,295.43,295.43,1003,73,2.65,153
36,36,Suzhou,Clouds,10000,300.04,300.04,300.04,1004,57,3.29,172
37,37,Suzhou,Clear,10000,305.23,305.23,305.23,1004,37,4.30,183
38,38,Suzhou,Clear,10000,307.39,307.39,307.39,1002,27,4.55,177
39,39,Suzhou,Clear,10000,305.35,305.35,305.35,1003,30,5.04,159

In [77]:
#cities_weather_df.to_csv("cities_weather_forecast.csv", index=False)

For more details about HTTP requests with `httr`, please refer to the previous HTTP request notebook here: 

[HTTP request in R](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/M4_Working_With_Data/lab2_jupyter_http-request.ipynb)

## TASK: Download datasets as csv files from cloud storage

The last task of this lab is straightforward: download some aggregated datasets from cloud storage

In [ ]:
# # Download several datasets

# # Download some general city information such as name and locations
# url <- "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/datasets/raw_worldcities.csv"
# # download the file
# download.file(url, destfile = "raw_worldcities.csv")

# # Download a specific hourly Seoul bike sharing demand dataset
# url <- "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/datasets/raw_seoul_bike_sharing.csv"
# # download the file
# download.file(url, destfile = "raw_seoul_bike_sharing.csv")

## Next Step

Now you should collect all datasets required for this project, all in csv format. Feel free to explore them preliminarily now. However, they are the raw datasets and have to be processed for further data visualization or data analysis.

In the next module, you will improve their quality by performing data wrangling tasks.

## Authors

<a href="https://www.linkedin.com/in/yan-luo-96288783/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkRP0321ENSkillsNetwork25371262-2021-01-01" target="_blank">Yan Luo</a>

### Other Contributors

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By | Change Description      |
| ----------------- | ------- | ---------- | ----------------------- |
| 2021-04-05        | 0.1     | Yan        | Initial version created |
|                   |         |            |                         |
|                   |         |            |                         |

## <h3 align="center"> © IBM Corporation 2021. All rights reserved. <h3/>